/* eslint-disable */
// ไฟล์นี้ถูกสร้างอัตโนมัติโดย scripts/generate-placeholders.mjs — อย่าแก้ด้วยมือ
// รันใหม่ด้วย: npm run placeholders

export type PlaceholderName = keyof typeof PLACEHOLDERS;

export const PLACEHOLDERS = {
  "hero-forge": { url: "/placeholder/hero-forge.svg", width: 1200, height: 1500, label: "ช่างกำลังตีมีดในเตาไฟ (ภาพ/วิดีโอหลักหน้าแรก)" },
  "forge-wide": { url: "/placeholder/forge-wide.svg", width: 1600, height: 900, label: "บรรยากาศซุ้มตีมีดบ้านต้นโพธิ์" },
  "forge-quench": { url: "/placeholder/forge-quench.svg", width: 1600, height: 900, label: "ขั้นตอนชุบแข็งใบมีดในน้ำมัน" },
  "forge-hammer": { url: "/placeholder/forge-hammer.svg", width: 1200, height: 900, label: "การตีขึ้นรูปด้วยค้อน" },
  "forge-sharpen": { url: "/placeholder/forge-sharpen.svg", width: 1200, height: 1000, label: "ครูช่างกำลังลับคมมีด" },
  "product-chef-1": { url: "/placeholder/product-chef-1.svg", width: 1200, height: 1200, label: "มีดแล่เนื้ออรัญญิก — ภาพรวมทั้งเล่ม" },
  "product-chef-2": { url: "/placeholder/product-chef-2.svg", width: 1200, height: 1200, label: "มีดแล่เนื้ออรัญญิก — รายละเอียดใบมีด" },
  "product-chef-3": { url: "/placeholder/product-chef-3.svg", width: 1200, height: 1200, label: "มีดแล่เนื้ออรัญญิก — ด้ามไม้ประดู่" },
  "product-chef-4": { url: "/placeholder/product-chef-4.svg", width: 1200, height: 1200, label: "มีดแล่เนื้ออรัญญิก — ขณะใช้งานจริง" },
  "product-bushcraft-1": { url: "/placeholder/product-bushcraft-1.svg", width: 1200, height: 1200, label: "มีดเดินป่าทรงคลาสสิก — ภาพรวม" },
  "product-bushcraft-2": { url: "/placeholder/product-bushcraft-2.svg", width: 1200, height: 1200, label: "มีดเดินป่าทรงคลาสสิก — ซองหนังแท้" },
  "product-bushcraft-3": { url: "/placeholder/product-bushcraft-3.svg", width: 1200, height: 1200, label: "มีดเดินป่าทรงคลาสสิก — สันมีดและคม" },
  "product-damascus-1": { url: "/placeholder/product-damascus-1.svg", width: 1200, height: 1200, label: "มีดพับเหล็กดามัสกัส — ภาพรวม" },
  "product-damascus-2": { url: "/placeholder/product-damascus-2.svg", width: 1200, height: 1200, label: "มีดพับเหล็กดามัสกัส — ลายเหล็กดามัสกัส" },
  "product-damascus-3": { url: "/placeholder/product-damascus-3.svg", width: 1200, height: 1200, label: "มีดพับเหล็กดามัสกัส — ขณะพับเก็บ" },
  "product-santoku-1": { url: "/placeholder/product-santoku-1.svg", width: 1200, height: 1200, label: "มีดซันโตกุเหล็ก D2 — ภาพรวม" },
  "product-santoku-2": { url: "/placeholder/product-santoku-2.svg", width: 1200, height: 1200, label: "มีดซันโตกุเหล็ก D2 — คมมีด" },
  "product-cleaver-1": { url: "/placeholder/product-cleaver-1.svg", width: 1200, height: 1200, label: "มีดอีโต้ครัวไทย — ภาพรวม" },
  "product-cleaver-2": { url: "/placeholder/product-cleaver-2.svg", width: 1200, height: 1200, label: "มีดอีโต้ครัวไทย — ด้ามจับ" },
  "product-sword-1": { url: "/placeholder/product-sword-1.svg", width: 1200, height: 1200, label: "ดาบมงคลสะสม — ภาพรวมทั้งเล่ม" },
  "product-sword-2": { url: "/placeholder/product-sword-2.svg", width: 1200, height: 1200, label: "ดาบมงคลสะสม — ฝักไม้แกะสลัก" },
  "product-sword-3": { url: "/placeholder/product-sword-3.svg", width: 1200, height: 1200, label: "ดาบมงคลสะสม — ลวดลายบนใบดาบ" },
  "product-keychain-1": { url: "/placeholder/product-keychain-1.svg", width: 1200, height: 1200, label: "พวงกุญแจมีดจิ๋ว — ภาพรวม" },
  "product-keychain-2": { url: "/placeholder/product-keychain-2.svg", width: 1200, height: 1200, label: "พวงกุญแจมีดจิ๋ว — เทียบขนาดกับมือ" },
  "product-chili-1": { url: "/placeholder/product-chili-1.svg", width: 1200, height: 1200, label: "น้ำพริกเผาสูตรชุมชน — ภาพสินค้า" },
  "product-chili-2": { url: "/placeholder/product-chili-2.svg", width: 1200, height: 1200, label: "น้ำพริกเผาสูตรชุมชน — วัตถุดิบ" },
  "craftsman-somchai": { url: "/placeholder/craftsman-somchai.svg", width: 800, height: 800, label: "ครูช่างสมชาย — ภาพโปรไฟล์" },
  "craftsman-prasert": { url: "/placeholder/craftsman-prasert.svg", width: 800, height: 800, label: "ช่างประเสริฐ — ภาพโปรไฟล์" },
  "craftsman-wanpen": { url: "/placeholder/craftsman-wanpen.svg", width: 800, height: 800, label: "ช่างวันเพ็ญ — ภาพโปรไฟล์" },
  "craftsman-thawee": { url: "/placeholder/craftsman-thawee.svg", width: 800, height: 800, label: "ช่างทวี — ภาพโปรไฟล์" },
  "article-steel-sound": { url: "/placeholder/article-steel-sound.svg", width: 1600, height: 900, label: "ปกบทความ: ภูมิปัญญาการฟังเสียงเหล็ก" },
  "article-history": { url: "/placeholder/article-history.svg", width: 1600, height: 900, label: "ปกบทความ: ประวัติชุมชนบ้านต้นโพธิ์" },
  "article-festival": { url: "/placeholder/article-festival.svg", width: 1600, height: 900, label: "ปกบทความ: งานประจำปีของชุมชน" },
  "article-knife-care": { url: "/placeholder/article-knife-care.svg", width: 1600, height: 900, label: "ปกบทความ: วิธีดูแลรักษามีด" },
  "article-rice-field": { url: "/placeholder/article-rice-field.svg", width: 1600, height: 900, label: "ปกบทความ: วิถีเกษตรริมแม่น้ำป่าสัก" },
  "article-workshop-open": { url: "/placeholder/article-workshop-open.svg", width: 1600, height: 900, label: "ปกบทความ: เปิดฐานเรียนรู้การตีมีด" },
  "article-inline-anvil": { url: "/placeholder/article-inline-anvil.svg", width: 1400, height: 900, label: "ภาพประกอบบทความ: ทั่งตีเหล็กโบราณ" },
  "article-inline-charcoal": { url: "/placeholder/article-inline-charcoal.svg", width: 1400, height: 900, label: "ภาพประกอบบทความ: ถ่านไม้สำหรับเตาเผา" },
  "workshop-forge": { url: "/placeholder/workshop-forge.svg", width: 1200, height: 800, label: "ฐานเรียนรู้การตีมีด" },
  "workshop-handle": { url: "/placeholder/workshop-handle.svg", width: 1200, height: 800, label: "ฐานเรียนรู้การเข้าด้ามและทำซองหนัง" },
  "workshop-farm": { url: "/placeholder/workshop-farm.svg", width: 1200, height: 800, label: "ฐานเรียนรู้วิถีเกษตรและอาหารพื้นบ้าน" },
  "place-homestay": { url: "/placeholder/place-homestay.svg", width: 1200, height: 800, label: "โฮมสเตย์บ้านต้นโพธิ์" },
  "place-temple": { url: "/placeholder/place-temple.svg", width: 1200, height: 800, label: "วัดประจำชุมชน — จุดเช็กอิน" },
  "place-market": { url: "/placeholder/place-market.svg", width: 1200, height: 800, label: "ตลาดชุมชนและร้านของฝาก" },
  "about-heritage": { url: "/placeholder/about-heritage.svg", width: 1400, height: 1000, label: "ภาพประวัติศาสตร์ชุมชนช่างตีเหล็ก" },
  "about-community": { url: "/placeholder/about-community.svg", width: 1600, height: 900, label: "ภาพรวมชุมชนบ้านต้นโพธิ์" },
} as const;
