/* eslint-disable */
// ไฟล์นี้ถูกสร้างอัตโนมัติโดย scripts/generate-placeholders.mjs — อย่าแก้ด้วยมือ
// รันใหม่ด้วย: npm run placeholders

export type PlaceholderName = keyof typeof PLACEHOLDERS;

export const PLACEHOLDERS = {
  "hero-herbal": { url: "/placeholder/hero-herbal.svg", width: 1200, height: 1500, label: "กลุ่มแม่บ้านกำลังแปรรูปสมุนไพร (ภาพ/วิดีโอหลักหน้าแรก)" },
  "community-wide": { url: "/placeholder/community-wide.svg", width: 1600, height: 900, label: "บรรยากาศชุมชนบ้านต้นโพธิ์ริมแม่น้ำเจ้าพระยา" },
  "herb-garden": { url: "/placeholder/herb-garden.svg", width: 1600, height: 900, label: "แปลงสมุนไพรของชุมชน" },
  "herb-drying": { url: "/placeholder/herb-drying.svg", width: 1200, height: 900, label: "การตากและอบสมุนไพรก่อนแปรรูป" },
  "herb-blending": { url: "/placeholder/herb-blending.svg", width: 1200, height: 1000, label: "การผสมตำรับยาหม่องน้ำ" },
  "product-balm-1": { url: "/placeholder/product-balm-1.svg", width: 1200, height: 1200, label: "ยาหม่องน้ำสมุนไพรบ้านต้นโพธิ์ — ภาพรวมขวด" },
  "product-balm-2": { url: "/placeholder/product-balm-2.svg", width: 1200, height: 1200, label: "ยาหม่องน้ำสมุนไพรบ้านต้นโพธิ์ — ฉลากและปริมาณสุทธิ" },
  "product-balm-3": { url: "/placeholder/product-balm-3.svg", width: 1200, height: 1200, label: "ยาหม่องน้ำสมุนไพรบ้านต้นโพธิ์ — ขณะใช้งาน" },
  "product-solidbalm-1": { url: "/placeholder/product-solidbalm-1.svg", width: 1200, height: 1200, label: "ยาหม่องสมุนไพรแบบตลับ — ภาพรวม" },
  "product-solidbalm-2": { url: "/placeholder/product-solidbalm-2.svg", width: 1200, height: 1200, label: "ยาหม่องสมุนไพรแบบตลับ — เปิดฝาเห็นเนื้อยาหม่อง" },
  "product-oil-1": { url: "/placeholder/product-oil-1.svg", width: 1200, height: 1200, label: "น้ำมันไพลนวดคลายกล้ามเนื้อ — ภาพรวม" },
  "product-oil-2": { url: "/placeholder/product-oil-2.svg", width: 1200, height: 1200, label: "น้ำมันไพลนวดคลายกล้ามเนื้อ — เทียบขนาดกับฝ่ามือ" },
  "product-compress-1": { url: "/placeholder/product-compress-1.svg", width: 1200, height: 1200, label: "ลูกประคบสมุนไพรสด — ภาพรวม" },
  "product-compress-2": { url: "/placeholder/product-compress-2.svg", width: 1200, height: 1200, label: "ลูกประคบสมุนไพรสด — สมุนไพรที่ใช้ภายใน" },
  "product-compress-3": { url: "/placeholder/product-compress-3.svg", width: 1200, height: 1200, label: "ลูกประคบสมุนไพรสด — ขณะนึ่งก่อนใช้" },
  "product-inhaler-1": { url: "/placeholder/product-inhaler-1.svg", width: 1200, height: 1200, label: "ยาดมสมุนไพรแบบหลอด — ภาพรวม" },
  "product-inhaler-2": { url: "/placeholder/product-inhaler-2.svg", width: 1200, height: 1200, label: "ยาดมสมุนไพรแบบหลอด — สมุนไพรภายในหลอด" },
  "product-soap-1": { url: "/placeholder/product-soap-1.svg", width: 1200, height: 1200, label: "สบู่สมุนไพรกลุ่มแม่บ้าน — ภาพรวม" },
  "product-soap-2": { url: "/placeholder/product-soap-2.svg", width: 1200, height: 1200, label: "สบู่สมุนไพรกลุ่มแม่บ้าน — ผิวสบู่ใกล้ ๆ" },
  "product-tea-1": { url: "/placeholder/product-tea-1.svg", width: 1200, height: 1200, label: "ชาสมุนไพรชงดื่ม — ภาพรวมบรรจุภัณฑ์" },
  "product-tea-2": { url: "/placeholder/product-tea-2.svg", width: 1200, height: 1200, label: "ชาสมุนไพรชงดื่ม — ขณะชงในถ้วย" },
  "product-giftset-1": { url: "/placeholder/product-giftset-1.svg", width: 1200, height: 1200, label: "ชุดของฝากสมุนไพรบ้านต้นโพธิ์ — ภาพรวมทั้งชุด" },
  "product-giftset-2": { url: "/placeholder/product-giftset-2.svg", width: 1200, height: 1200, label: "ชุดของฝากสมุนไพรบ้านต้นโพธิ์ — กล่องบรรจุ" },
  "product-rice-1": { url: "/placeholder/product-rice-1.svg", width: 1200, height: 1200, label: "ข้าวสารจากแปลงนาของชุมชน — ภาพสินค้า" },
  "product-rice-2": { url: "/placeholder/product-rice-2.svg", width: 1200, height: 1200, label: "ข้าวสารจากแปลงนาของชุมชน — แปลงนา 15 ไร่" },
  "member-pimsiri": { url: "/placeholder/member-pimsiri.svg", width: 800, height: 800, label: "นางพิมสิริ กัลวิชา ปราชญ์ชุมชนด้านการแปรรูปสมุนไพร — ภาพโปรไฟล์" },
  "member-pathummarat": { url: "/placeholder/member-pathummarat.svg", width: 800, height: 800, label: "นางปทุมมรัตน์ ธรรมโม ประธานกลุ่มวิสาหกิจชุมชนสมุนไพร — ภาพโปรไฟล์" },
  "article-mon-heritage": { url: "/placeholder/article-mon-heritage.svg", width: 1600, height: 900, label: "ปกบทความ: รากเหง้าชาวมอญบ้านต้นโพธิ์" },
  "article-wat-chetwong": { url: "/placeholder/article-wat-chetwong.svg", width: 1600, height: 900, label: "ปกบทความ: วัดเจตวงศ์ โบราณสถานริมเจ้าพระยา" },
  "article-herbal-wisdom": { url: "/placeholder/article-herbal-wisdom.svg", width: 1600, height: 900, label: "ปกบทความ: ภูมิปัญญาสมุนไพรของชุมชน" },
  "article-name-origin": { url: "/placeholder/article-name-origin.svg", width: 1600, height: 900, label: "ปกบทความ: ที่มาของชื่อบ้านต้นโพธิ์" },
  "article-sufficiency": { url: "/placeholder/article-sufficiency.svg", width: 1600, height: 900, label: "ปกบทความ: ศูนย์เรียนรู้เศรษฐกิจพอเพียง" },
  "article-riverside": { url: "/placeholder/article-riverside.svg", width: 1600, height: 900, label: "ปกบทความ: จุดชมทัศนียภาพริมแม่น้ำเจ้าพระยา" },
  "article-inline-mortar": { url: "/placeholder/article-inline-mortar.svg", width: 1400, height: 900, label: "ภาพประกอบบทความ: ครกบดสมุนไพรของชุมชน" },
  "article-inline-ubosot": { url: "/placeholder/article-inline-ubosot.svg", width: 1400, height: 900, label: "ภาพประกอบบทความ: อุโบสถมหาอุตของวัดเจตวงศ์" },
  "workshop-balm": { url: "/placeholder/workshop-balm.svg", width: 1200, height: 800, label: "ฐานเรียนรู้การทำยาหม่องน้ำสมุนไพร" },
  "workshop-compress": { url: "/placeholder/workshop-compress.svg", width: 1200, height: 800, label: "ฐานเรียนรู้การทำลูกประคบสมุนไพร" },
  "workshop-mon-walk": { url: "/placeholder/workshop-mon-walk.svg", width: 1200, height: 800, label: "กิจกรรมเดินชมวัดเจตวงศ์และวิถีมอญริมน้ำ" },
  "place-wat-chetwong": { url: "/placeholder/place-wat-chetwong.svg", width: 1200, height: 800, label: "วัดเจตวงศ์ — โบราณสถานประจำชุมชน" },
  "place-learning-center": { url: "/placeholder/place-learning-center.svg", width: 1200, height: 800, label: "ศูนย์การเรียนรู้เศรษฐกิจพอเพียงบ้านต้นโพธิ์" },
  "place-viewpoint": { url: "/placeholder/place-viewpoint.svg", width: 1200, height: 800, label: "จุดชมทัศนียภาพริมฝั่งแม่น้ำเจ้าพระยา" },
  "place-enterprise": { url: "/placeholder/place-enterprise.svg", width: 1200, height: 800, label: "จุดจำหน่ายผลิตภัณฑ์วิสาหกิจชุมชนสมุนไพร" },
  "about-heritage": { url: "/placeholder/about-heritage.svg", width: 1400, height: 1000, label: "ภาพประวัติศาสตร์ชุมชนมอญริมเจ้าพระยา" },
  "about-community": { url: "/placeholder/about-community.svg", width: 1600, height: 900, label: "ภาพรวมชุมชนบ้านต้นโพธิ์" },
} as const;
