import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-sqlite'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.run(sql`ALTER TABLE \`pages_blocks_prose\` ADD \`card_color\` text;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_image_text\` ADD \`card_color\` text;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_cards\` ADD \`card_color\` text;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_stats\` ADD \`card_color\` text;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_gallery\` ADD \`card_color\` text;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_collection\` ADD \`card_color\` text;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_cta\` ADD \`card_color\` text;`)
  await db.run(sql`ALTER TABLE \`pages\` ADD \`hero_background\` text DEFAULT 'dark';`)
  await db.run(sql`ALTER TABLE \`pages\` ADD \`hero_background_color\` text;`)
  await db.run(sql`ALTER TABLE \`pages\` ADD \`hero_text_tone\` text DEFAULT 'auto';`)
  await db.run(sql`ALTER TABLE \`pages\` ADD \`hero_accent_color\` text;`)
  await db.run(sql`ALTER TABLE \`pages\` ADD \`page_style_accent_color\` text;`)
  await db.run(sql`ALTER TABLE \`pages\` ADD \`page_style_background_color\` text;`)
  await db.run(sql`ALTER TABLE \`pages\` ADD \`page_style_card_color\` text;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_prose\` ADD \`card_color\` text;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_image_text\` ADD \`card_color\` text;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_cards\` ADD \`card_color\` text;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_stats\` ADD \`card_color\` text;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_gallery\` ADD \`card_color\` text;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_collection\` ADD \`card_color\` text;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_cta\` ADD \`card_color\` text;`)
  await db.run(sql`ALTER TABLE \`_pages_v\` ADD \`version_hero_background\` text DEFAULT 'dark';`)
  await db.run(sql`ALTER TABLE \`_pages_v\` ADD \`version_hero_background_color\` text;`)
  await db.run(sql`ALTER TABLE \`_pages_v\` ADD \`version_hero_text_tone\` text DEFAULT 'auto';`)
  await db.run(sql`ALTER TABLE \`_pages_v\` ADD \`version_hero_accent_color\` text;`)
  await db.run(sql`ALTER TABLE \`_pages_v\` ADD \`version_page_style_accent_color\` text;`)
  await db.run(sql`ALTER TABLE \`_pages_v\` ADD \`version_page_style_background_color\` text;`)
  await db.run(sql`ALTER TABLE \`_pages_v\` ADD \`version_page_style_card_color\` text;`)
  await db.run(sql`ALTER TABLE \`theme\` ADD \`header_background\` text DEFAULT 'dark';`)
  await db.run(sql`ALTER TABLE \`theme\` ADD \`header_background_color\` text;`)
  await db.run(sql`ALTER TABLE \`theme\` ADD \`header_text_tone\` text DEFAULT 'auto';`)
  await db.run(sql`ALTER TABLE \`theme\` ADD \`header_accent_color\` text;`)
  await db.run(sql`ALTER TABLE \`theme\` ADD \`footer_background\` text DEFAULT 'dark';`)
  await db.run(sql`ALTER TABLE \`theme\` ADD \`footer_background_color\` text;`)
  await db.run(sql`ALTER TABLE \`theme\` ADD \`footer_text_tone\` text DEFAULT 'auto';`)
  await db.run(sql`ALTER TABLE \`theme\` ADD \`footer_accent_color\` text;`)
  await db.run(sql`ALTER TABLE \`_theme_v\` ADD \`version_header_background\` text DEFAULT 'dark';`)
  await db.run(sql`ALTER TABLE \`_theme_v\` ADD \`version_header_background_color\` text;`)
  await db.run(sql`ALTER TABLE \`_theme_v\` ADD \`version_header_text_tone\` text DEFAULT 'auto';`)
  await db.run(sql`ALTER TABLE \`_theme_v\` ADD \`version_header_accent_color\` text;`)
  await db.run(sql`ALTER TABLE \`_theme_v\` ADD \`version_footer_background\` text DEFAULT 'dark';`)
  await db.run(sql`ALTER TABLE \`_theme_v\` ADD \`version_footer_background_color\` text;`)
  await db.run(sql`ALTER TABLE \`_theme_v\` ADD \`version_footer_text_tone\` text DEFAULT 'auto';`)
  await db.run(sql`ALTER TABLE \`_theme_v\` ADD \`version_footer_accent_color\` text;`)
  await db.run(sql`ALTER TABLE \`home_page_sections\` ADD \`card_color\` text;`)
  await db.run(sql`ALTER TABLE \`home_page\` ADD \`hero_background\` text DEFAULT 'dark';`)
  await db.run(sql`ALTER TABLE \`home_page\` ADD \`hero_background_color\` text;`)
  await db.run(sql`ALTER TABLE \`home_page\` ADD \`hero_text_tone\` text DEFAULT 'auto';`)
  await db.run(sql`ALTER TABLE \`home_page\` ADD \`hero_accent_color\` text;`)
  await db.run(sql`ALTER TABLE \`home_page\` ADD \`page_style_accent_color\` text;`)
  await db.run(sql`ALTER TABLE \`home_page\` ADD \`page_style_background_color\` text;`)
  await db.run(sql`ALTER TABLE \`home_page\` ADD \`page_style_card_color\` text;`)
  await db.run(sql`ALTER TABLE \`_home_page_v_version_sections\` ADD \`card_color\` text;`)
  await db.run(sql`ALTER TABLE \`_home_page_v\` ADD \`version_hero_background\` text DEFAULT 'dark';`)
  await db.run(sql`ALTER TABLE \`_home_page_v\` ADD \`version_hero_background_color\` text;`)
  await db.run(sql`ALTER TABLE \`_home_page_v\` ADD \`version_hero_text_tone\` text DEFAULT 'auto';`)
  await db.run(sql`ALTER TABLE \`_home_page_v\` ADD \`version_hero_accent_color\` text;`)
  await db.run(sql`ALTER TABLE \`_home_page_v\` ADD \`version_page_style_accent_color\` text;`)
  await db.run(sql`ALTER TABLE \`_home_page_v\` ADD \`version_page_style_background_color\` text;`)
  await db.run(sql`ALTER TABLE \`_home_page_v\` ADD \`version_page_style_card_color\` text;`)
  await db.run(sql`ALTER TABLE \`about_page_sections\` ADD \`card_color\` text;`)
  await db.run(sql`ALTER TABLE \`about_page\` ADD \`hero_background\` text DEFAULT 'dark';`)
  await db.run(sql`ALTER TABLE \`about_page\` ADD \`hero_background_color\` text;`)
  await db.run(sql`ALTER TABLE \`about_page\` ADD \`hero_text_tone\` text DEFAULT 'auto';`)
  await db.run(sql`ALTER TABLE \`about_page\` ADD \`hero_accent_color\` text;`)
  await db.run(sql`ALTER TABLE \`about_page\` ADD \`page_style_accent_color\` text;`)
  await db.run(sql`ALTER TABLE \`about_page\` ADD \`page_style_background_color\` text;`)
  await db.run(sql`ALTER TABLE \`about_page\` ADD \`page_style_card_color\` text;`)
  await db.run(sql`ALTER TABLE \`_about_page_v_version_sections\` ADD \`card_color\` text;`)
  await db.run(sql`ALTER TABLE \`_about_page_v\` ADD \`version_hero_background\` text DEFAULT 'dark';`)
  await db.run(sql`ALTER TABLE \`_about_page_v\` ADD \`version_hero_background_color\` text;`)
  await db.run(sql`ALTER TABLE \`_about_page_v\` ADD \`version_hero_text_tone\` text DEFAULT 'auto';`)
  await db.run(sql`ALTER TABLE \`_about_page_v\` ADD \`version_hero_accent_color\` text;`)
  await db.run(sql`ALTER TABLE \`_about_page_v\` ADD \`version_page_style_accent_color\` text;`)
  await db.run(sql`ALTER TABLE \`_about_page_v\` ADD \`version_page_style_background_color\` text;`)
  await db.run(sql`ALTER TABLE \`_about_page_v\` ADD \`version_page_style_card_color\` text;`)
  await db.run(sql`ALTER TABLE \`shop_page_sections\` ADD \`card_color\` text;`)
  await db.run(sql`ALTER TABLE \`shop_page\` ADD \`hero_background\` text DEFAULT 'dark';`)
  await db.run(sql`ALTER TABLE \`shop_page\` ADD \`hero_background_color\` text;`)
  await db.run(sql`ALTER TABLE \`shop_page\` ADD \`hero_text_tone\` text DEFAULT 'auto';`)
  await db.run(sql`ALTER TABLE \`shop_page\` ADD \`hero_accent_color\` text;`)
  await db.run(sql`ALTER TABLE \`shop_page\` ADD \`page_style_accent_color\` text;`)
  await db.run(sql`ALTER TABLE \`shop_page\` ADD \`page_style_background_color\` text;`)
  await db.run(sql`ALTER TABLE \`shop_page\` ADD \`page_style_card_color\` text;`)
  await db.run(sql`ALTER TABLE \`_shop_page_v_version_sections\` ADD \`card_color\` text;`)
  await db.run(sql`ALTER TABLE \`_shop_page_v\` ADD \`version_hero_background\` text DEFAULT 'dark';`)
  await db.run(sql`ALTER TABLE \`_shop_page_v\` ADD \`version_hero_background_color\` text;`)
  await db.run(sql`ALTER TABLE \`_shop_page_v\` ADD \`version_hero_text_tone\` text DEFAULT 'auto';`)
  await db.run(sql`ALTER TABLE \`_shop_page_v\` ADD \`version_hero_accent_color\` text;`)
  await db.run(sql`ALTER TABLE \`_shop_page_v\` ADD \`version_page_style_accent_color\` text;`)
  await db.run(sql`ALTER TABLE \`_shop_page_v\` ADD \`version_page_style_background_color\` text;`)
  await db.run(sql`ALTER TABLE \`_shop_page_v\` ADD \`version_page_style_card_color\` text;`)
  await db.run(sql`ALTER TABLE \`stories_page_sections\` ADD \`card_color\` text;`)
  await db.run(sql`ALTER TABLE \`stories_page\` ADD \`hero_background\` text DEFAULT 'dark';`)
  await db.run(sql`ALTER TABLE \`stories_page\` ADD \`hero_background_color\` text;`)
  await db.run(sql`ALTER TABLE \`stories_page\` ADD \`hero_text_tone\` text DEFAULT 'auto';`)
  await db.run(sql`ALTER TABLE \`stories_page\` ADD \`hero_accent_color\` text;`)
  await db.run(sql`ALTER TABLE \`stories_page\` ADD \`page_style_accent_color\` text;`)
  await db.run(sql`ALTER TABLE \`stories_page\` ADD \`page_style_background_color\` text;`)
  await db.run(sql`ALTER TABLE \`stories_page\` ADD \`page_style_card_color\` text;`)
  await db.run(sql`ALTER TABLE \`_stories_page_v_version_sections\` ADD \`card_color\` text;`)
  await db.run(sql`ALTER TABLE \`_stories_page_v\` ADD \`version_hero_background\` text DEFAULT 'dark';`)
  await db.run(sql`ALTER TABLE \`_stories_page_v\` ADD \`version_hero_background_color\` text;`)
  await db.run(sql`ALTER TABLE \`_stories_page_v\` ADD \`version_hero_text_tone\` text DEFAULT 'auto';`)
  await db.run(sql`ALTER TABLE \`_stories_page_v\` ADD \`version_hero_accent_color\` text;`)
  await db.run(sql`ALTER TABLE \`_stories_page_v\` ADD \`version_page_style_accent_color\` text;`)
  await db.run(sql`ALTER TABLE \`_stories_page_v\` ADD \`version_page_style_background_color\` text;`)
  await db.run(sql`ALTER TABLE \`_stories_page_v\` ADD \`version_page_style_card_color\` text;`)
  await db.run(sql`ALTER TABLE \`tourism_page_sections\` ADD \`card_color\` text;`)
  await db.run(sql`ALTER TABLE \`tourism_page\` ADD \`hero_background\` text DEFAULT 'dark';`)
  await db.run(sql`ALTER TABLE \`tourism_page\` ADD \`hero_background_color\` text;`)
  await db.run(sql`ALTER TABLE \`tourism_page\` ADD \`hero_text_tone\` text DEFAULT 'auto';`)
  await db.run(sql`ALTER TABLE \`tourism_page\` ADD \`hero_accent_color\` text;`)
  await db.run(sql`ALTER TABLE \`tourism_page\` ADD \`page_style_accent_color\` text;`)
  await db.run(sql`ALTER TABLE \`tourism_page\` ADD \`page_style_background_color\` text;`)
  await db.run(sql`ALTER TABLE \`tourism_page\` ADD \`page_style_card_color\` text;`)
  await db.run(sql`ALTER TABLE \`_tourism_page_v_version_sections\` ADD \`card_color\` text;`)
  await db.run(sql`ALTER TABLE \`_tourism_page_v\` ADD \`version_hero_background\` text DEFAULT 'dark';`)
  await db.run(sql`ALTER TABLE \`_tourism_page_v\` ADD \`version_hero_background_color\` text;`)
  await db.run(sql`ALTER TABLE \`_tourism_page_v\` ADD \`version_hero_text_tone\` text DEFAULT 'auto';`)
  await db.run(sql`ALTER TABLE \`_tourism_page_v\` ADD \`version_hero_accent_color\` text;`)
  await db.run(sql`ALTER TABLE \`_tourism_page_v\` ADD \`version_page_style_accent_color\` text;`)
  await db.run(sql`ALTER TABLE \`_tourism_page_v\` ADD \`version_page_style_background_color\` text;`)
  await db.run(sql`ALTER TABLE \`_tourism_page_v\` ADD \`version_page_style_card_color\` text;`)
  await db.run(sql`ALTER TABLE \`contact_page_sections\` ADD \`card_color\` text;`)
  await db.run(sql`ALTER TABLE \`contact_page\` ADD \`hero_background\` text DEFAULT 'dark';`)
  await db.run(sql`ALTER TABLE \`contact_page\` ADD \`hero_background_color\` text;`)
  await db.run(sql`ALTER TABLE \`contact_page\` ADD \`hero_text_tone\` text DEFAULT 'auto';`)
  await db.run(sql`ALTER TABLE \`contact_page\` ADD \`hero_accent_color\` text;`)
  await db.run(sql`ALTER TABLE \`contact_page\` ADD \`page_style_accent_color\` text;`)
  await db.run(sql`ALTER TABLE \`contact_page\` ADD \`page_style_background_color\` text;`)
  await db.run(sql`ALTER TABLE \`contact_page\` ADD \`page_style_card_color\` text;`)
  await db.run(sql`ALTER TABLE \`_contact_page_v_version_sections\` ADD \`card_color\` text;`)
  await db.run(sql`ALTER TABLE \`_contact_page_v\` ADD \`version_hero_background\` text DEFAULT 'dark';`)
  await db.run(sql`ALTER TABLE \`_contact_page_v\` ADD \`version_hero_background_color\` text;`)
  await db.run(sql`ALTER TABLE \`_contact_page_v\` ADD \`version_hero_text_tone\` text DEFAULT 'auto';`)
  await db.run(sql`ALTER TABLE \`_contact_page_v\` ADD \`version_hero_accent_color\` text;`)
  await db.run(sql`ALTER TABLE \`_contact_page_v\` ADD \`version_page_style_accent_color\` text;`)
  await db.run(sql`ALTER TABLE \`_contact_page_v\` ADD \`version_page_style_background_color\` text;`)
  await db.run(sql`ALTER TABLE \`_contact_page_v\` ADD \`version_page_style_card_color\` text;`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.run(sql`ALTER TABLE \`pages_blocks_prose\` DROP COLUMN \`card_color\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_image_text\` DROP COLUMN \`card_color\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_cards\` DROP COLUMN \`card_color\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_stats\` DROP COLUMN \`card_color\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_gallery\` DROP COLUMN \`card_color\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_collection\` DROP COLUMN \`card_color\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_cta\` DROP COLUMN \`card_color\`;`)
  await db.run(sql`ALTER TABLE \`pages\` DROP COLUMN \`hero_background\`;`)
  await db.run(sql`ALTER TABLE \`pages\` DROP COLUMN \`hero_background_color\`;`)
  await db.run(sql`ALTER TABLE \`pages\` DROP COLUMN \`hero_text_tone\`;`)
  await db.run(sql`ALTER TABLE \`pages\` DROP COLUMN \`hero_accent_color\`;`)
  await db.run(sql`ALTER TABLE \`pages\` DROP COLUMN \`page_style_accent_color\`;`)
  await db.run(sql`ALTER TABLE \`pages\` DROP COLUMN \`page_style_background_color\`;`)
  await db.run(sql`ALTER TABLE \`pages\` DROP COLUMN \`page_style_card_color\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_prose\` DROP COLUMN \`card_color\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_image_text\` DROP COLUMN \`card_color\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_cards\` DROP COLUMN \`card_color\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_stats\` DROP COLUMN \`card_color\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_gallery\` DROP COLUMN \`card_color\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_collection\` DROP COLUMN \`card_color\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_cta\` DROP COLUMN \`card_color\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v\` DROP COLUMN \`version_hero_background\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v\` DROP COLUMN \`version_hero_background_color\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v\` DROP COLUMN \`version_hero_text_tone\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v\` DROP COLUMN \`version_hero_accent_color\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v\` DROP COLUMN \`version_page_style_accent_color\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v\` DROP COLUMN \`version_page_style_background_color\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v\` DROP COLUMN \`version_page_style_card_color\`;`)
  await db.run(sql`ALTER TABLE \`theme\` DROP COLUMN \`header_background\`;`)
  await db.run(sql`ALTER TABLE \`theme\` DROP COLUMN \`header_background_color\`;`)
  await db.run(sql`ALTER TABLE \`theme\` DROP COLUMN \`header_text_tone\`;`)
  await db.run(sql`ALTER TABLE \`theme\` DROP COLUMN \`header_accent_color\`;`)
  await db.run(sql`ALTER TABLE \`theme\` DROP COLUMN \`footer_background\`;`)
  await db.run(sql`ALTER TABLE \`theme\` DROP COLUMN \`footer_background_color\`;`)
  await db.run(sql`ALTER TABLE \`theme\` DROP COLUMN \`footer_text_tone\`;`)
  await db.run(sql`ALTER TABLE \`theme\` DROP COLUMN \`footer_accent_color\`;`)
  await db.run(sql`ALTER TABLE \`_theme_v\` DROP COLUMN \`version_header_background\`;`)
  await db.run(sql`ALTER TABLE \`_theme_v\` DROP COLUMN \`version_header_background_color\`;`)
  await db.run(sql`ALTER TABLE \`_theme_v\` DROP COLUMN \`version_header_text_tone\`;`)
  await db.run(sql`ALTER TABLE \`_theme_v\` DROP COLUMN \`version_header_accent_color\`;`)
  await db.run(sql`ALTER TABLE \`_theme_v\` DROP COLUMN \`version_footer_background\`;`)
  await db.run(sql`ALTER TABLE \`_theme_v\` DROP COLUMN \`version_footer_background_color\`;`)
  await db.run(sql`ALTER TABLE \`_theme_v\` DROP COLUMN \`version_footer_text_tone\`;`)
  await db.run(sql`ALTER TABLE \`_theme_v\` DROP COLUMN \`version_footer_accent_color\`;`)
  await db.run(sql`ALTER TABLE \`home_page_sections\` DROP COLUMN \`card_color\`;`)
  await db.run(sql`ALTER TABLE \`home_page\` DROP COLUMN \`hero_background\`;`)
  await db.run(sql`ALTER TABLE \`home_page\` DROP COLUMN \`hero_background_color\`;`)
  await db.run(sql`ALTER TABLE \`home_page\` DROP COLUMN \`hero_text_tone\`;`)
  await db.run(sql`ALTER TABLE \`home_page\` DROP COLUMN \`hero_accent_color\`;`)
  await db.run(sql`ALTER TABLE \`home_page\` DROP COLUMN \`page_style_accent_color\`;`)
  await db.run(sql`ALTER TABLE \`home_page\` DROP COLUMN \`page_style_background_color\`;`)
  await db.run(sql`ALTER TABLE \`home_page\` DROP COLUMN \`page_style_card_color\`;`)
  await db.run(sql`ALTER TABLE \`_home_page_v_version_sections\` DROP COLUMN \`card_color\`;`)
  await db.run(sql`ALTER TABLE \`_home_page_v\` DROP COLUMN \`version_hero_background\`;`)
  await db.run(sql`ALTER TABLE \`_home_page_v\` DROP COLUMN \`version_hero_background_color\`;`)
  await db.run(sql`ALTER TABLE \`_home_page_v\` DROP COLUMN \`version_hero_text_tone\`;`)
  await db.run(sql`ALTER TABLE \`_home_page_v\` DROP COLUMN \`version_hero_accent_color\`;`)
  await db.run(sql`ALTER TABLE \`_home_page_v\` DROP COLUMN \`version_page_style_accent_color\`;`)
  await db.run(sql`ALTER TABLE \`_home_page_v\` DROP COLUMN \`version_page_style_background_color\`;`)
  await db.run(sql`ALTER TABLE \`_home_page_v\` DROP COLUMN \`version_page_style_card_color\`;`)
  await db.run(sql`ALTER TABLE \`about_page_sections\` DROP COLUMN \`card_color\`;`)
  await db.run(sql`ALTER TABLE \`about_page\` DROP COLUMN \`hero_background\`;`)
  await db.run(sql`ALTER TABLE \`about_page\` DROP COLUMN \`hero_background_color\`;`)
  await db.run(sql`ALTER TABLE \`about_page\` DROP COLUMN \`hero_text_tone\`;`)
  await db.run(sql`ALTER TABLE \`about_page\` DROP COLUMN \`hero_accent_color\`;`)
  await db.run(sql`ALTER TABLE \`about_page\` DROP COLUMN \`page_style_accent_color\`;`)
  await db.run(sql`ALTER TABLE \`about_page\` DROP COLUMN \`page_style_background_color\`;`)
  await db.run(sql`ALTER TABLE \`about_page\` DROP COLUMN \`page_style_card_color\`;`)
  await db.run(sql`ALTER TABLE \`_about_page_v_version_sections\` DROP COLUMN \`card_color\`;`)
  await db.run(sql`ALTER TABLE \`_about_page_v\` DROP COLUMN \`version_hero_background\`;`)
  await db.run(sql`ALTER TABLE \`_about_page_v\` DROP COLUMN \`version_hero_background_color\`;`)
  await db.run(sql`ALTER TABLE \`_about_page_v\` DROP COLUMN \`version_hero_text_tone\`;`)
  await db.run(sql`ALTER TABLE \`_about_page_v\` DROP COLUMN \`version_hero_accent_color\`;`)
  await db.run(sql`ALTER TABLE \`_about_page_v\` DROP COLUMN \`version_page_style_accent_color\`;`)
  await db.run(sql`ALTER TABLE \`_about_page_v\` DROP COLUMN \`version_page_style_background_color\`;`)
  await db.run(sql`ALTER TABLE \`_about_page_v\` DROP COLUMN \`version_page_style_card_color\`;`)
  await db.run(sql`ALTER TABLE \`shop_page_sections\` DROP COLUMN \`card_color\`;`)
  await db.run(sql`ALTER TABLE \`shop_page\` DROP COLUMN \`hero_background\`;`)
  await db.run(sql`ALTER TABLE \`shop_page\` DROP COLUMN \`hero_background_color\`;`)
  await db.run(sql`ALTER TABLE \`shop_page\` DROP COLUMN \`hero_text_tone\`;`)
  await db.run(sql`ALTER TABLE \`shop_page\` DROP COLUMN \`hero_accent_color\`;`)
  await db.run(sql`ALTER TABLE \`shop_page\` DROP COLUMN \`page_style_accent_color\`;`)
  await db.run(sql`ALTER TABLE \`shop_page\` DROP COLUMN \`page_style_background_color\`;`)
  await db.run(sql`ALTER TABLE \`shop_page\` DROP COLUMN \`page_style_card_color\`;`)
  await db.run(sql`ALTER TABLE \`_shop_page_v_version_sections\` DROP COLUMN \`card_color\`;`)
  await db.run(sql`ALTER TABLE \`_shop_page_v\` DROP COLUMN \`version_hero_background\`;`)
  await db.run(sql`ALTER TABLE \`_shop_page_v\` DROP COLUMN \`version_hero_background_color\`;`)
  await db.run(sql`ALTER TABLE \`_shop_page_v\` DROP COLUMN \`version_hero_text_tone\`;`)
  await db.run(sql`ALTER TABLE \`_shop_page_v\` DROP COLUMN \`version_hero_accent_color\`;`)
  await db.run(sql`ALTER TABLE \`_shop_page_v\` DROP COLUMN \`version_page_style_accent_color\`;`)
  await db.run(sql`ALTER TABLE \`_shop_page_v\` DROP COLUMN \`version_page_style_background_color\`;`)
  await db.run(sql`ALTER TABLE \`_shop_page_v\` DROP COLUMN \`version_page_style_card_color\`;`)
  await db.run(sql`ALTER TABLE \`stories_page_sections\` DROP COLUMN \`card_color\`;`)
  await db.run(sql`ALTER TABLE \`stories_page\` DROP COLUMN \`hero_background\`;`)
  await db.run(sql`ALTER TABLE \`stories_page\` DROP COLUMN \`hero_background_color\`;`)
  await db.run(sql`ALTER TABLE \`stories_page\` DROP COLUMN \`hero_text_tone\`;`)
  await db.run(sql`ALTER TABLE \`stories_page\` DROP COLUMN \`hero_accent_color\`;`)
  await db.run(sql`ALTER TABLE \`stories_page\` DROP COLUMN \`page_style_accent_color\`;`)
  await db.run(sql`ALTER TABLE \`stories_page\` DROP COLUMN \`page_style_background_color\`;`)
  await db.run(sql`ALTER TABLE \`stories_page\` DROP COLUMN \`page_style_card_color\`;`)
  await db.run(sql`ALTER TABLE \`_stories_page_v_version_sections\` DROP COLUMN \`card_color\`;`)
  await db.run(sql`ALTER TABLE \`_stories_page_v\` DROP COLUMN \`version_hero_background\`;`)
  await db.run(sql`ALTER TABLE \`_stories_page_v\` DROP COLUMN \`version_hero_background_color\`;`)
  await db.run(sql`ALTER TABLE \`_stories_page_v\` DROP COLUMN \`version_hero_text_tone\`;`)
  await db.run(sql`ALTER TABLE \`_stories_page_v\` DROP COLUMN \`version_hero_accent_color\`;`)
  await db.run(sql`ALTER TABLE \`_stories_page_v\` DROP COLUMN \`version_page_style_accent_color\`;`)
  await db.run(sql`ALTER TABLE \`_stories_page_v\` DROP COLUMN \`version_page_style_background_color\`;`)
  await db.run(sql`ALTER TABLE \`_stories_page_v\` DROP COLUMN \`version_page_style_card_color\`;`)
  await db.run(sql`ALTER TABLE \`tourism_page_sections\` DROP COLUMN \`card_color\`;`)
  await db.run(sql`ALTER TABLE \`tourism_page\` DROP COLUMN \`hero_background\`;`)
  await db.run(sql`ALTER TABLE \`tourism_page\` DROP COLUMN \`hero_background_color\`;`)
  await db.run(sql`ALTER TABLE \`tourism_page\` DROP COLUMN \`hero_text_tone\`;`)
  await db.run(sql`ALTER TABLE \`tourism_page\` DROP COLUMN \`hero_accent_color\`;`)
  await db.run(sql`ALTER TABLE \`tourism_page\` DROP COLUMN \`page_style_accent_color\`;`)
  await db.run(sql`ALTER TABLE \`tourism_page\` DROP COLUMN \`page_style_background_color\`;`)
  await db.run(sql`ALTER TABLE \`tourism_page\` DROP COLUMN \`page_style_card_color\`;`)
  await db.run(sql`ALTER TABLE \`_tourism_page_v_version_sections\` DROP COLUMN \`card_color\`;`)
  await db.run(sql`ALTER TABLE \`_tourism_page_v\` DROP COLUMN \`version_hero_background\`;`)
  await db.run(sql`ALTER TABLE \`_tourism_page_v\` DROP COLUMN \`version_hero_background_color\`;`)
  await db.run(sql`ALTER TABLE \`_tourism_page_v\` DROP COLUMN \`version_hero_text_tone\`;`)
  await db.run(sql`ALTER TABLE \`_tourism_page_v\` DROP COLUMN \`version_hero_accent_color\`;`)
  await db.run(sql`ALTER TABLE \`_tourism_page_v\` DROP COLUMN \`version_page_style_accent_color\`;`)
  await db.run(sql`ALTER TABLE \`_tourism_page_v\` DROP COLUMN \`version_page_style_background_color\`;`)
  await db.run(sql`ALTER TABLE \`_tourism_page_v\` DROP COLUMN \`version_page_style_card_color\`;`)
  await db.run(sql`ALTER TABLE \`contact_page_sections\` DROP COLUMN \`card_color\`;`)
  await db.run(sql`ALTER TABLE \`contact_page\` DROP COLUMN \`hero_background\`;`)
  await db.run(sql`ALTER TABLE \`contact_page\` DROP COLUMN \`hero_background_color\`;`)
  await db.run(sql`ALTER TABLE \`contact_page\` DROP COLUMN \`hero_text_tone\`;`)
  await db.run(sql`ALTER TABLE \`contact_page\` DROP COLUMN \`hero_accent_color\`;`)
  await db.run(sql`ALTER TABLE \`contact_page\` DROP COLUMN \`page_style_accent_color\`;`)
  await db.run(sql`ALTER TABLE \`contact_page\` DROP COLUMN \`page_style_background_color\`;`)
  await db.run(sql`ALTER TABLE \`contact_page\` DROP COLUMN \`page_style_card_color\`;`)
  await db.run(sql`ALTER TABLE \`_contact_page_v_version_sections\` DROP COLUMN \`card_color\`;`)
  await db.run(sql`ALTER TABLE \`_contact_page_v\` DROP COLUMN \`version_hero_background\`;`)
  await db.run(sql`ALTER TABLE \`_contact_page_v\` DROP COLUMN \`version_hero_background_color\`;`)
  await db.run(sql`ALTER TABLE \`_contact_page_v\` DROP COLUMN \`version_hero_text_tone\`;`)
  await db.run(sql`ALTER TABLE \`_contact_page_v\` DROP COLUMN \`version_hero_accent_color\`;`)
  await db.run(sql`ALTER TABLE \`_contact_page_v\` DROP COLUMN \`version_page_style_accent_color\`;`)
  await db.run(sql`ALTER TABLE \`_contact_page_v\` DROP COLUMN \`version_page_style_background_color\`;`)
  await db.run(sql`ALTER TABLE \`_contact_page_v\` DROP COLUMN \`version_page_style_card_color\`;`)
}
