/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    artisans: Artisan;
    products: Product;
    articles: Article;
    workshops: Workshop;
    places: Place;
    pages: Page;
    enquiries: Enquiry;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    artisans: ArtisansSelect<false> | ArtisansSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    workshops: WorkshopsSelect<false> | WorkshopsSelect<true>;
    places: PlacesSelect<false> | PlacesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('th' | 'en') | ('th' | 'en')[];
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    theme: Theme;
    'ui-labels': UiLabel;
    'seo-settings': SeoSetting;
    'home-page': HomePage;
    'about-page': AboutPage;
    'shop-page': ShopPage;
    'stories-page': StoriesPage;
    'tourism-page': TourismPage;
    'contact-page': ContactPage;
    'not-found-page': NotFoundPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    theme: ThemeSelect<false> | ThemeSelect<true>;
    'ui-labels': UiLabelsSelect<false> | UiLabelsSelect<true>;
    'seo-settings': SeoSettingsSelect<false> | SeoSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'shop-page': ShopPageSelect<false> | ShopPageSelect<true>;
    'stories-page': StoriesPageSelect<false> | StoriesPageSelect<true>;
    'tourism-page': TourismPageSelect<false> | TourismPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'not-found-page': NotFoundPageSelect<false> | NotFoundPageSelect<true>;
  };
  locale: 'th' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * ชื่อนี้จะขึ้นในประวัติการแก้ไขเนื้อหา
   */
  name: string;
  role: 'admin' | 'editor' | 'viewer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * รูปทั้งหมดที่ใช้บนเว็บไซต์
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * อธิบายว่าในภาพมีอะไร สำหรับผู้ใช้โปรแกรมอ่านหน้าจอและเพื่อ SEO
   */
  alt: string;
  /**
   * เว้นว่างได้ ถ้าไม่ต้องการให้แสดงข้อความใต้ภาพ
   */
  caption?: string | null;
  /**
   * เช่น "ถ่ายโดยชุมชนบ้านต้นโพธิ์" หรือ "เทศบาลตำบลบางขะแยง (2567)"
   */
  credit: string;
  /**
   * รูปที่ยังไม่ได้ขออนุญาตจะถูกกันไม่ให้นำไปใช้ในเนื้อหา
   */
  usageRights: 'own' | 'licensed' | 'pending';
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * หมวดหมู่ใช้ร่วมกันทั้งสินค้าและบทความ แยกด้วยช่อง “ใช้กับ”
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * เว้นว่างได้ ระบบจะสร้างให้จากชื่อ — เปลี่ยนแล้วลิงก์เดิมจะใช้ไม่ได้
   */
  slug?: string | null;
  type: 'product' | 'article';
  description?: string | null;
  /**
   * เลขน้อยขึ้นก่อน
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artisans".
 */
export interface Artisan {
  id: number;
  name: string;
  /**
   * เว้นว่างได้ ระบบจะสร้างให้จากชื่อ — เปลี่ยนแล้วลิงก์เดิมจะใช้ไม่ได้
   */
  slug?: string | null;
  /**
   * เช่น "ประธานกลุ่มวิสาหกิจชุมชนสมุนไพรบ้านต้นโพธิ์"
   */
  title: string;
  specialty?: string | null;
  bio?: string | null;
  photo?: (number | null) | Media;
  /**
   * เช่น "วิกิชุมชน ศูนย์มานุษยวิทยาสิรินธร (2567)"
   */
  source?: string | null;
  consentBio: boolean;
  /**
   * ต้องติ๊กถ้ามีการใส่ภาพโปรไฟล์
   */
  consentPhoto?: boolean | null;
  consentDate?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  /**
   * ใช้บนการ์ดสินค้าและในผลการค้นหาของ Google
   */
  excerpt: string;
  category: number | Category;
  artisan: number | Artisan;
  /**
   * รูปแรกคือรูปหลักที่ใช้บนการ์ดและแคตตาล็อก
   */
  gallery: {
    image: number | Media;
    id?: string | null;
  }[];
  story?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * แสดงบนการ์ดและหน้าสินค้า ไม่ควรเกิน 4 ป้าย
   */
  badges?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * เว้นว่างไว้ถ้าต้องการให้ขึ้นว่า "สอบถามราคา"
   */
  price?: number | null;
  availability: 'in-stock' | 'made-to-order' | 'sold-out';
  /**
   * เช่น "แจ้งล่วงหน้าอย่างน้อย 7 วัน"
   */
  leadTime?: string | null;
  featured?: boolean | null;
  order?: number | null;
  form: 'liquid-balm' | 'solid-balm' | 'massage-oil' | 'compress' | 'soap' | 'tea' | 'dried-herb' | 'other';
  /**
   * เช่น "ขวดแก้ว 20 มล." หรือ "ลูกละ 100 กรัม"
   */
  netContent: string;
  mainHerbs?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  usage: {
    value: string;
    id?: string | null;
  }[];
  shelfLife?: string | null;
  careInstructions: {
    value: string;
    id?: string | null;
  }[];
  /**
   * ติ๊กแล้วหน้าสินค้าจะขึ้นกล่องเตือนอัตโนมัติ — ต้องไม่ติ๊กเฉพาะสินค้าที่รับประทานได้ เช่น ชาสมุนไพร
   */
  externalUseOnly?: boolean | null;
  registrationType?: ('none' | 'fda-cosmetic' | 'fda-herbal' | 'tcps') | null;
  /**
   * กฎหมายกำหนดให้แสดงเลขนี้ หากผลิตภัณฑ์ได้จดแจ้งไว้
   */
  registrationNo?: string | null;
  /**
   * เว้นว่างได้ ระบบจะสร้างให้จากชื่อ — เปลี่ยนแล้วลิงก์เดิมจะใช้ไม่ได้
   */
  slug?: string | null;
  /**
   * ใช้อ้างอิงตอนลูกค้าสั่งซื้อทาง LINE
   */
  sku: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  excerpt: string;
  coverImage: number | Media;
  category: number | Category;
  author: string;
  /**
   * ใส่เมื่อผู้เขียนอยู่ในทำเนียบ จะดึงภาพและประวัติมาแสดงท้ายบทความ
   */
  artisan?: (number | null) | Artisan;
  content: (
    | {
        text: string;
        level: '2' | '3';
        id?: string | null;
        blockName?: string | null;
        blockType: 'heading';
      }
    | {
        text: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'paragraph';
      }
    | {
        style: 'bullet' | 'number';
        items?:
          | {
              value: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'list';
      }
    | {
        media: number | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'image';
      }
    | {
        text: string;
        attribution?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'quote';
      }
    | {
        /**
         * ส่วนหลัง v= ในลิงก์ เช่น dQw4w9WgXcQ
         */
        videoId: string;
        title: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'youtube';
      }
  )[];
  /**
   * เว้นว่างได้ ระบบจะสร้างให้จากชื่อ — เปลี่ยนแล้วลิงก์เดิมจะใช้ไม่ได้
   */
  slug?: string | null;
  publishedAt: string;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workshops".
 */
export interface Workshop {
  id: number;
  title: string;
  /**
   * เว้นว่างได้ ระบบจะสร้างให้จากชื่อ — เปลี่ยนแล้วลิงก์เดิมจะใช้ไม่ได้
   */
  slug?: string | null;
  summary: string;
  image: number | Media;
  description: {
    value: string;
    id?: string | null;
  }[];
  duration: string;
  /**
   * เว้นว่างไว้ถ้าต้องการให้ขึ้นว่า "สอบถามราคา"
   */
  pricePerPerson?: number | null;
  minParticipants: number;
  maxParticipants: number;
  bookingNotes?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  takeaway?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "places".
 */
export interface Place {
  id: number;
  name: string;
  /**
   * เว้นว่างได้ ระบบจะสร้างให้จากชื่อ — เปลี่ยนแล้วลิงก์เดิมจะใช้ไม่ได้
   */
  slug?: string | null;
  kind: 'workshop-site' | 'homestay' | 'landmark' | 'shop';
  description: string;
  openingHours?: string | null;
  image: number | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * สร้างหน้าใหม่ได้เองโดยไม่ต้องแก้โค้ด · หน้าใหม่จะอยู่ที่ที่อยู่เว็บ /ชื่อลิงก์ และเพิ่มเข้าเมนูได้จากหน้า “เมนูนำทาง”
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    eyebrow?: string | null;
    title: string;
    description?: string | null;
    /**
     * เลือกได้เฉพาะฟอนต์ที่โหลดมาพร้อมเว็บแล้ว จึงไม่ทำให้เว็บช้าลง
     */
    fontFamily?: ('theme' | 'plex-noto' | 'sarabun-trirong' | 'prompt') | null;
    /**
     * ย่อ-ขยายตัวอักษรทุกขนาดในส่วนนี้พร้อมกัน สัดส่วนหัวเรื่องกับเนื้อหาจึงไม่เพี้ยน
     */
    textScale?: ('0.9' | '0.95' | '1' | '1.1' | '1.2') | null;
    textAlign?: ('default' | 'left' | 'center' | 'right') | null;
    contentWidth?: ('default' | 'narrow' | 'medium' | 'full') | null;
    /**
     * ปรับระยะห่างบน-ล่างและช่องไฟระหว่างการ์ดในส่วนนี้
     */
    spacing?: ('default' | 'compact' | 'normal' | 'roomy') | null;
  };
  /**
   * ลากเพื่อสลับลำดับ · แต่ละส่วนปรับสี ฟอนต์ และการจัดวางของตัวเองได้ในกล่องพับด้านล่างของส่วนนั้น
   */
  layout: (
    | {
        content: (
          | {
              text: string;
              level: '2' | '3';
              id?: string | null;
              blockName?: string | null;
              blockType: 'heading';
            }
          | {
              text: string;
              id?: string | null;
              blockName?: string | null;
              blockType: 'paragraph';
            }
          | {
              style: 'bullet' | 'number';
              items?:
                | {
                    value: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'list';
            }
        )[];
        background?: ('page' | 'dark' | 'tint' | 'custom') | null;
        /**
         * ใส่เป็นรหัสสีแบบ #rrggbb
         */
        backgroundColor?: string | null;
        textTone?: ('auto' | 'light' | 'dark') | null;
        /**
         * เว้นว่างไว้เพื่อใช้สีหลักของธีม · ใส่แล้วจะเปลี่ยนสีปุ่มและป้ายเฉพาะในส่วนนี้
         */
        accentColor?: string | null;
        /**
         * เลือกได้เฉพาะฟอนต์ที่โหลดมาพร้อมเว็บแล้ว จึงไม่ทำให้เว็บช้าลง
         */
        fontFamily?: ('theme' | 'plex-noto' | 'sarabun-trirong' | 'prompt') | null;
        /**
         * ย่อ-ขยายตัวอักษรทุกขนาดในส่วนนี้พร้อมกัน สัดส่วนหัวเรื่องกับเนื้อหาจึงไม่เพี้ยน
         */
        textScale?: ('0.9' | '0.95' | '1' | '1.1' | '1.2') | null;
        textAlign?: ('default' | 'left' | 'center' | 'right') | null;
        contentWidth?: ('default' | 'narrow' | 'medium' | 'full') | null;
        /**
         * ปรับระยะห่างบน-ล่างและช่องไฟระหว่างการ์ดในส่วนนี้
         */
        spacing?: ('default' | 'compact' | 'normal' | 'roomy') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'prose';
      }
    | {
        image: number | Media;
        imagePosition?: ('left' | 'right') | null;
        title: string;
        body: string;
        button?: {
          label?: string | null;
          /**
           * เช่น /shop
           */
          href?: string | null;
        };
        background?: ('page' | 'dark' | 'tint' | 'custom') | null;
        /**
         * ใส่เป็นรหัสสีแบบ #rrggbb
         */
        backgroundColor?: string | null;
        textTone?: ('auto' | 'light' | 'dark') | null;
        /**
         * เว้นว่างไว้เพื่อใช้สีหลักของธีม · ใส่แล้วจะเปลี่ยนสีปุ่มและป้ายเฉพาะในส่วนนี้
         */
        accentColor?: string | null;
        /**
         * เลือกได้เฉพาะฟอนต์ที่โหลดมาพร้อมเว็บแล้ว จึงไม่ทำให้เว็บช้าลง
         */
        fontFamily?: ('theme' | 'plex-noto' | 'sarabun-trirong' | 'prompt') | null;
        /**
         * ย่อ-ขยายตัวอักษรทุกขนาดในส่วนนี้พร้อมกัน สัดส่วนหัวเรื่องกับเนื้อหาจึงไม่เพี้ยน
         */
        textScale?: ('0.9' | '0.95' | '1' | '1.1' | '1.2') | null;
        textAlign?: ('default' | 'left' | 'center' | 'right') | null;
        contentWidth?: ('default' | 'narrow' | 'medium' | 'full') | null;
        /**
         * ปรับระยะห่างบน-ล่างและช่องไฟระหว่างการ์ดในส่วนนี้
         */
        spacing?: ('default' | 'compact' | 'normal' | 'roomy') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'imageText';
      }
    | {
        heading: {
          eyebrow?: string | null;
          title: string;
          description?: string | null;
        };
        items: {
          icon?: ('leaf' | 'temple' | 'mortar' | 'users' | 'map-pin' | 'none') | null;
          title: string;
          body: string;
          id?: string | null;
        }[];
        background?: ('page' | 'dark' | 'tint' | 'custom') | null;
        /**
         * ใส่เป็นรหัสสีแบบ #rrggbb
         */
        backgroundColor?: string | null;
        textTone?: ('auto' | 'light' | 'dark') | null;
        /**
         * เว้นว่างไว้เพื่อใช้สีหลักของธีม · ใส่แล้วจะเปลี่ยนสีปุ่มและป้ายเฉพาะในส่วนนี้
         */
        accentColor?: string | null;
        columns?: ('auto' | '2' | '3' | '4') | null;
        /**
         * เลือกได้เฉพาะฟอนต์ที่โหลดมาพร้อมเว็บแล้ว จึงไม่ทำให้เว็บช้าลง
         */
        fontFamily?: ('theme' | 'plex-noto' | 'sarabun-trirong' | 'prompt') | null;
        /**
         * ย่อ-ขยายตัวอักษรทุกขนาดในส่วนนี้พร้อมกัน สัดส่วนหัวเรื่องกับเนื้อหาจึงไม่เพี้ยน
         */
        textScale?: ('0.9' | '0.95' | '1' | '1.1' | '1.2') | null;
        textAlign?: ('default' | 'left' | 'center' | 'right') | null;
        contentWidth?: ('default' | 'narrow' | 'medium' | 'full') | null;
        /**
         * ปรับระยะห่างบน-ล่างและช่องไฟระหว่างการ์ดในส่วนนี้
         */
        spacing?: ('default' | 'compact' | 'normal' | 'roomy') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'cards';
      }
    | {
        heading: {
          eyebrow?: string | null;
          title: string;
          description?: string | null;
        };
        items: {
          value: string;
          label: string;
          id?: string | null;
        }[];
        background?: ('page' | 'dark' | 'tint' | 'custom') | null;
        /**
         * ใส่เป็นรหัสสีแบบ #rrggbb
         */
        backgroundColor?: string | null;
        textTone?: ('auto' | 'light' | 'dark') | null;
        /**
         * เว้นว่างไว้เพื่อใช้สีหลักของธีม · ใส่แล้วจะเปลี่ยนสีปุ่มและป้ายเฉพาะในส่วนนี้
         */
        accentColor?: string | null;
        columns?: ('auto' | '2' | '3' | '4') | null;
        /**
         * เลือกได้เฉพาะฟอนต์ที่โหลดมาพร้อมเว็บแล้ว จึงไม่ทำให้เว็บช้าลง
         */
        fontFamily?: ('theme' | 'plex-noto' | 'sarabun-trirong' | 'prompt') | null;
        /**
         * ย่อ-ขยายตัวอักษรทุกขนาดในส่วนนี้พร้อมกัน สัดส่วนหัวเรื่องกับเนื้อหาจึงไม่เพี้ยน
         */
        textScale?: ('0.9' | '0.95' | '1' | '1.1' | '1.2') | null;
        textAlign?: ('default' | 'left' | 'center' | 'right') | null;
        contentWidth?: ('default' | 'narrow' | 'medium' | 'full') | null;
        /**
         * ปรับระยะห่างบน-ล่างและช่องไฟระหว่างการ์ดในส่วนนี้
         */
        spacing?: ('default' | 'compact' | 'normal' | 'roomy') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'stats';
      }
    | {
        heading: {
          eyebrow?: string | null;
          title: string;
          description?: string | null;
        };
        images: {
          image: number | Media;
          id?: string | null;
        }[];
        background?: ('page' | 'dark' | 'tint' | 'custom') | null;
        /**
         * ใส่เป็นรหัสสีแบบ #rrggbb
         */
        backgroundColor?: string | null;
        textTone?: ('auto' | 'light' | 'dark') | null;
        /**
         * เว้นว่างไว้เพื่อใช้สีหลักของธีม · ใส่แล้วจะเปลี่ยนสีปุ่มและป้ายเฉพาะในส่วนนี้
         */
        accentColor?: string | null;
        columns?: ('auto' | '2' | '3' | '4') | null;
        /**
         * เลือกได้เฉพาะฟอนต์ที่โหลดมาพร้อมเว็บแล้ว จึงไม่ทำให้เว็บช้าลง
         */
        fontFamily?: ('theme' | 'plex-noto' | 'sarabun-trirong' | 'prompt') | null;
        /**
         * ย่อ-ขยายตัวอักษรทุกขนาดในส่วนนี้พร้อมกัน สัดส่วนหัวเรื่องกับเนื้อหาจึงไม่เพี้ยน
         */
        textScale?: ('0.9' | '0.95' | '1' | '1.1' | '1.2') | null;
        textAlign?: ('default' | 'left' | 'center' | 'right') | null;
        contentWidth?: ('default' | 'narrow' | 'medium' | 'full') | null;
        /**
         * ปรับระยะห่างบน-ล่างและช่องไฟระหว่างการ์ดในส่วนนี้
         */
        spacing?: ('default' | 'compact' | 'normal' | 'roomy') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'gallery';
      }
    | {
        heading: {
          eyebrow?: string | null;
          title: string;
          description?: string | null;
        };
        source: 'products' | 'articles' | 'workshops' | 'places';
        /**
         * เว้นว่างไว้เพื่อแสดงทั้งหมด
         */
        limit?: number | null;
        link?: {
          label?: string | null;
          href?: string | null;
        };
        background?: ('page' | 'dark' | 'tint' | 'custom') | null;
        /**
         * ใส่เป็นรหัสสีแบบ #rrggbb
         */
        backgroundColor?: string | null;
        textTone?: ('auto' | 'light' | 'dark') | null;
        /**
         * เว้นว่างไว้เพื่อใช้สีหลักของธีม · ใส่แล้วจะเปลี่ยนสีปุ่มและป้ายเฉพาะในส่วนนี้
         */
        accentColor?: string | null;
        columns?: ('auto' | '2' | '3' | '4') | null;
        /**
         * เลือกได้เฉพาะฟอนต์ที่โหลดมาพร้อมเว็บแล้ว จึงไม่ทำให้เว็บช้าลง
         */
        fontFamily?: ('theme' | 'plex-noto' | 'sarabun-trirong' | 'prompt') | null;
        /**
         * ย่อ-ขยายตัวอักษรทุกขนาดในส่วนนี้พร้อมกัน สัดส่วนหัวเรื่องกับเนื้อหาจึงไม่เพี้ยน
         */
        textScale?: ('0.9' | '0.95' | '1' | '1.1' | '1.2') | null;
        textAlign?: ('default' | 'left' | 'center' | 'right') | null;
        contentWidth?: ('default' | 'narrow' | 'medium' | 'full') | null;
        /**
         * ปรับระยะห่างบน-ล่างและช่องไฟระหว่างการ์ดในส่วนนี้
         */
        spacing?: ('default' | 'compact' | 'normal' | 'roomy') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'collection';
      }
    | {
        eyebrow?: string | null;
        title: string;
        body?: string | null;
        background?: ('page' | 'dark' | 'tint' | 'custom') | null;
        /**
         * ใส่เป็นรหัสสีแบบ #rrggbb
         */
        backgroundColor?: string | null;
        textTone?: ('auto' | 'light' | 'dark') | null;
        /**
         * เว้นว่างไว้เพื่อใช้สีหลักของธีม · ใส่แล้วจะเปลี่ยนสีปุ่มและป้ายเฉพาะในส่วนนี้
         */
        accentColor?: string | null;
        /**
         * เลือกได้เฉพาะฟอนต์ที่โหลดมาพร้อมเว็บแล้ว จึงไม่ทำให้เว็บช้าลง
         */
        fontFamily?: ('theme' | 'plex-noto' | 'sarabun-trirong' | 'prompt') | null;
        /**
         * ย่อ-ขยายตัวอักษรทุกขนาดในส่วนนี้พร้อมกัน สัดส่วนหัวเรื่องกับเนื้อหาจึงไม่เพี้ยน
         */
        textScale?: ('0.9' | '0.95' | '1' | '1.1' | '1.2') | null;
        textAlign?: ('default' | 'left' | 'center' | 'right') | null;
        contentWidth?: ('default' | 'narrow' | 'medium' | 'full') | null;
        /**
         * ปรับระยะห่างบน-ล่างและช่องไฟระหว่างการ์ดในส่วนนี้
         */
        spacing?: ('default' | 'compact' | 'normal' | 'roomy') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'cta';
      }
  )[];
  /**
   * เว้นว่างได้ ระบบจะใช้คำโปรยของแถบหัวหน้าเพจแทน
   */
  seoDescription?: string | null;
  seoImage?: (number | null) | Media;
  /**
   * ติ๊กออกสำหรับหน้าที่ต้องการให้เข้าถึงด้วยลิงก์ตรงเท่านั้น
   */
  showInSitemap?: boolean | null;
  /**
   * ที่อยู่ของหน้านี้ เช่น ใส่ activity จะได้ /activity · เว้นว่างได้ ระบบจะสร้างให้จากชื่อหน้า · เปลี่ยนแล้วลิงก์เดิมจะใช้ไม่ได้ ให้เพิ่ม “ทางเปลี่ยนเส้นทาง” ไว้ด้วย
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * ข้อความที่ส่งเข้ามาจากฟอร์มติดต่อบนหน้าเว็บ
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  name: string;
  phone: string;
  topic: string;
  message: string;
  status: 'new' | 'contacted' | 'closed';
  /**
   * เห็นเฉพาะผู้ดูแล ไม่แสดงบนเว็บ
   */
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * เมื่อเปลี่ยนชื่อลิงก์ (slug) หรือลบหน้าทิ้ง ให้เพิ่มรายการที่นี่ ลิงก์เก่าที่เคยแชร์ไว้จะพาไปหน้าใหม่แทนที่จะเจอหน้า 404
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * ใส่เฉพาะส่วนหลังชื่อโดเมน เช่น /shop/old-balm · ต้องขึ้นต้นด้วย /
   */
  from: string;
  /**
   * เส้นทางในเว็บ เช่น /shop/new-balm หรือลิงก์เต็มที่ขึ้นต้นด้วย https://
   */
  to: string;
  /**
   * ติ๊กไว้เมื่อย้ายถาวร (308) — Google จะโอนอันดับของลิงก์เก่าไปให้หน้าใหม่ · ติ๊กออกเมื่อย้ายชั่วคราว (307)
   */
  permanent?: boolean | null;
  /**
   * ติ๊กออกเพื่อหยุดใช้ชั่วคราวโดยไม่ต้องลบทิ้ง
   */
  enabled?: boolean | null;
  /**
   * เช่น “เปลี่ยนชื่อสินค้าเมื่อ ก.ย. 2569” เพื่อให้คนอื่นรู้ที่มา
   */
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'artisans';
        value: number | Artisan;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'workshops';
        value: number | Workshop;
      } | null)
    | ({
        relationTo: 'places';
        value: number | Place;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  usageRights?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artisans_select".
 */
export interface ArtisansSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  title?: T;
  specialty?: T;
  bio?: T;
  photo?: T;
  source?: T;
  consentBio?: T;
  consentPhoto?: T;
  consentDate?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  excerpt?: T;
  category?: T;
  artisan?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  story?:
    | T
    | {
        value?: T;
        id?: T;
      };
  badges?:
    | T
    | {
        value?: T;
        id?: T;
      };
  price?: T;
  availability?: T;
  leadTime?: T;
  featured?: T;
  order?: T;
  form?: T;
  netContent?: T;
  mainHerbs?:
    | T
    | {
        value?: T;
        id?: T;
      };
  usage?:
    | T
    | {
        value?: T;
        id?: T;
      };
  shelfLife?: T;
  careInstructions?:
    | T
    | {
        value?: T;
        id?: T;
      };
  externalUseOnly?: T;
  registrationType?: T;
  registrationNo?: T;
  slug?: T;
  sku?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  coverImage?: T;
  category?: T;
  author?: T;
  artisan?: T;
  content?:
    | T
    | {
        heading?:
          | T
          | {
              text?: T;
              level?: T;
              id?: T;
              blockName?: T;
            };
        paragraph?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        list?:
          | T
          | {
              style?: T;
              items?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              media?: T;
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              text?: T;
              attribution?: T;
              id?: T;
              blockName?: T;
            };
        youtube?:
          | T
          | {
              videoId?: T;
              title?: T;
              id?: T;
              blockName?: T;
            };
      };
  slug?: T;
  publishedAt?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workshops_select".
 */
export interface WorkshopsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  image?: T;
  description?:
    | T
    | {
        value?: T;
        id?: T;
      };
  duration?: T;
  pricePerPerson?: T;
  minParticipants?: T;
  maxParticipants?: T;
  bookingNotes?:
    | T
    | {
        value?: T;
        id?: T;
      };
  takeaway?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "places_select".
 */
export interface PlacesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  kind?: T;
  description?: T;
  openingHours?: T;
  image?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        fontFamily?: T;
        textScale?: T;
        textAlign?: T;
        contentWidth?: T;
        spacing?: T;
      };
  layout?:
    | T
    | {
        prose?:
          | T
          | {
              content?:
                | T
                | {
                    heading?:
                      | T
                      | {
                          text?: T;
                          level?: T;
                          id?: T;
                          blockName?: T;
                        };
                    paragraph?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                          blockName?: T;
                        };
                    list?:
                      | T
                      | {
                          style?: T;
                          items?:
                            | T
                            | {
                                value?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                  };
              background?: T;
              backgroundColor?: T;
              textTone?: T;
              accentColor?: T;
              fontFamily?: T;
              textScale?: T;
              textAlign?: T;
              contentWidth?: T;
              spacing?: T;
              id?: T;
              blockName?: T;
            };
        imageText?:
          | T
          | {
              image?: T;
              imagePosition?: T;
              title?: T;
              body?: T;
              button?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              background?: T;
              backgroundColor?: T;
              textTone?: T;
              accentColor?: T;
              fontFamily?: T;
              textScale?: T;
              textAlign?: T;
              contentWidth?: T;
              spacing?: T;
              id?: T;
              blockName?: T;
            };
        cards?:
          | T
          | {
              heading?:
                | T
                | {
                    eyebrow?: T;
                    title?: T;
                    description?: T;
                  };
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              background?: T;
              backgroundColor?: T;
              textTone?: T;
              accentColor?: T;
              columns?: T;
              fontFamily?: T;
              textScale?: T;
              textAlign?: T;
              contentWidth?: T;
              spacing?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              heading?:
                | T
                | {
                    eyebrow?: T;
                    title?: T;
                    description?: T;
                  };
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              background?: T;
              backgroundColor?: T;
              textTone?: T;
              accentColor?: T;
              columns?: T;
              fontFamily?: T;
              textScale?: T;
              textAlign?: T;
              contentWidth?: T;
              spacing?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              heading?:
                | T
                | {
                    eyebrow?: T;
                    title?: T;
                    description?: T;
                  };
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              background?: T;
              backgroundColor?: T;
              textTone?: T;
              accentColor?: T;
              columns?: T;
              fontFamily?: T;
              textScale?: T;
              textAlign?: T;
              contentWidth?: T;
              spacing?: T;
              id?: T;
              blockName?: T;
            };
        collection?:
          | T
          | {
              heading?:
                | T
                | {
                    eyebrow?: T;
                    title?: T;
                    description?: T;
                  };
              source?: T;
              limit?: T;
              link?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              background?: T;
              backgroundColor?: T;
              textTone?: T;
              accentColor?: T;
              columns?: T;
              fontFamily?: T;
              textScale?: T;
              textAlign?: T;
              contentWidth?: T;
              spacing?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              body?: T;
              background?: T;
              backgroundColor?: T;
              textTone?: T;
              accentColor?: T;
              fontFamily?: T;
              textScale?: T;
              textAlign?: T;
              contentWidth?: T;
              spacing?: T;
              id?: T;
              blockName?: T;
            };
      };
  seoDescription?: T;
  seoImage?: T;
  showInSitemap?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  topic?: T;
  message?: T;
  status?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  permanent?: T;
  enabled?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * ชื่อ ข้อมูลติดต่อ ที่ตั้ง และเวลาทำการ ใช้ทั้งเว็บ
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  communityName: string;
  communityShortName: string;
  tagline: string;
  /**
   * แสดงบนแถบเมนูและท้ายเว็บตามสัดส่วนจริงของรูป (ไม่ตัดขอบ) · พื้นหลังตรงนั้นเป็นสีเข้ม ใช้ PNG พื้นโปร่งใสจะดูดีที่สุด — ถ้าว่างจะใช้ใบโพธิ์
   */
  logo?: (number | null) | Media;
  /**
   * รูปเล็กบนแท็บเบราว์เซอร์และหน้าจอโทรศัพท์ ใช้ PNG สี่เหลี่ยมจัตุรัสอย่างน้อย 512×512 — ถ้าว่างจะใช้โลโก้
   */
  favicon?: (number | null) | Media;
  /**
   * ใช้ท้ายเว็บ และเป็นคำอธิบายเว็บไซต์ในผลค้นหา Google
   */
  aboutSummary: string;
  /**
   * รูปแบบสากล เช่น +66818220774
   */
  phone: string;
  /**
   * เช่น 08-1822-0774
   */
  phoneDisplay: string;
  lineId: string;
  lineUrl: string;
  facebookUrl: string;
  email: string;
  address: string;
  addressLocality: string;
  addressRegion: string;
  postalCode: string;
  mapLatitude: number;
  mapLongitude: number;
  openingHours: string;
  /**
   * ใช้ในที่แคบ เช่น เมนูบนมือถือและแถบท้ายเว็บ
   */
  openingHoursShort: string;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * แก้เมนูบน ปุ่มติดต่อ และเมนูท้ายเว็บ
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  mainMenu?:
    | {
        label: string;
        linkType: 'page' | 'custom' | 'external' | 'dropdown';
        page?: ('/' | '/about' | '/stories' | '/shop' | '/tourism' | '/contact') | null;
        customPage?: (number | null) | Page;
        /**
         * ต้องขึ้นต้นด้วย https://
         */
        url?: string | null;
        children?:
          | {
              label: string;
              linkType: 'page' | 'custom' | 'external';
              page?: ('/' | '/about' | '/stories' | '/shop' | '/tourism' | '/contact') | null;
              customPage?: (number | null) | Page;
              /**
               * ต้องขึ้นต้นด้วย https://
               */
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  headerCta?: {
    enabled?: boolean | null;
    label?: string | null;
    action?: ('line' | 'phone' | 'contact') | null;
  };
  /**
   * ข้อความในเมนูที่เลื่อนออกมาเมื่อกดปุ่มสามขีดบนมือถือ
   */
  mobileMenu?: {
    title?: string | null;
    contactHeading?: string | null;
    /**
     * ระบบจะต่อท้ายด้วย LINE ID จากหน้าข้อมูลชุมชนให้เอง
     */
    lineButtonPrefix?: string | null;
    /**
     * ระบบจะต่อท้ายด้วยเบอร์โทรจากหน้าข้อมูลชุมชนให้เอง
     */
    phoneButtonPrefix?: string | null;
  };
  footerColumns?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              linkType: 'page' | 'custom' | 'external';
              page?: ('/' | '/about' | '/stories' | '/shop' | '/tourism' | '/contact') | null;
              customPage?: (number | null) | Page;
              /**
               * ต้องขึ้นต้นด้วย https://
               */
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * เปลี่ยนสี ตัวอักษร ความมน และความโปร่งของเว็บทั้งหมดจากที่นี่
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme".
 */
export interface Theme {
  id: number;
  palette: 'leaf' | 'ember' | 'indigo' | 'crimson' | 'custom';
  /**
   * ใส่เป็นรหัสสีแบบ #rrggbb เช่น #2e7d52 ระบบจะไล่เฉดอ่อน-เข้มให้เอง
   */
  accentColor?: string | null;
  surface: 'rice' | 'white' | 'grey';
  /**
   * ฟอนต์ถูกโหลดมาพร้อมเว็บ จึงเลือกได้เฉพาะในรายการนี้
   */
  fontPair: 'plex-noto' | 'sarabun-trirong' | 'prompt';
  /**
   * มีผลกับขนาดตัวอักษรทั้งเว็บพร้อมกัน
   */
  baseFontSize: '15' | '16' | '17' | '18';
  radius: 'sharp' | 'medium' | 'round';
  /**
   * ปรับระยะห่างทุกจุดในเว็บพร้อมกัน
   */
  density: 'compact' | 'normal' | 'airy';
  /**
   * ระบบจะกรอง @import, url() ที่ชี้ออกนอกเว็บ และแท็ก HTML ออกก่อนใช้งานเสมอ · จำกัด 8,000 ตัวอักษร · ถ้าเว็บเพี้ยน ให้ลบข้อความในช่องนี้แล้วบันทึกใหม่
   */
  customCss?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * คำเรียกที่ใช้ซ้ำทั้งเว็บ เช่น “ผลิตโดย” หรือ “เวลาทำการ” · เว้นว่างไว้จะใช้คำตั้งต้นของระบบ
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ui-labels".
 */
export interface UiLabel {
  id: number;
  general?: {
    askPrice?: string | null;
    askServicePrice?: string | null;
    viewAllProducts?: string | null;
    viewAllWorkshops?: string | null;
    viewAllArticles?: string | null;
    readFullArticle?: string | null;
    openInMaps?: string | null;
  };
  product?: {
    madeBy?: string | null;
    viewArtisans?: string | null;
    specs?: string | null;
    sku?: string | null;
    form?: string | null;
    netContent?: string | null;
    mainHerbs?: string | null;
    shelfLife?: string | null;
    externalUseTitle?: string | null;
    externalUseBody?: string | null;
    callGroup?: string | null;
    facebookHint?: string | null;
    storyEyebrow?: string | null;
    storyTitle?: string | null;
    usageEyebrow?: string | null;
    usageTitle?: string | null;
    careEyebrow?: string | null;
    careTitle?: string | null;
    relatedEyebrow?: string | null;
    relatedTitle?: string | null;
    filters?: string | null;
    sortBy?: string | null;
    resultsUnit?: string | null;
  };
  article?: {
    writtenBy?: string | null;
    readTime?: string | null;
    minutes?: string | null;
    share?: string | null;
    aboutAuthor?: string | null;
    aboutCommunityButton?: string | null;
    relatedEyebrow?: string | null;
    relatedTitle?: string | null;
    resultsUnit?: string | null;
  };
  tourism?: {
    duration?: string | null;
    participants?: string | null;
    participantsUnit?: string | null;
    price?: string | null;
    perPerson?: string | null;
    bookingTerms?: string | null;
    takeaway?: string | null;
    bookViaLine?: string | null;
    callToBook?: string | null;
  };
  contact?: {
    location?: string | null;
    openingHours?: string | null;
    coordinates?: string | null;
    contactCommunity?: string | null;
    directions?: string | null;
    copyright?: string | null;
  };
  about?: {
    role?: string | null;
    source?: string | null;
    references?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-settings".
 */
export interface SeoSetting {
  id: number;
  /**
   * ใช้ในแท็ก meta keywords
   */
  keywords?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * ใช้เมื่อหน้านั้นไม่มีภาพของตัวเอง
   */
  defaultOgImage?: (number | null) | Media;
  /**
   * เช่น G-XXXXXXXXXX — เว้นว่างไว้ถ้ายังไม่ใช้
   */
  ga4MeasurementId?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero: {
    eyebrow?: string | null;
    /**
     * แยกเป็นบรรทัดเองเพราะภาษาไทยไม่มีช่องว่างระหว่างคำ ถ้าปล่อยให้เบราว์เซอร์ตัดเองอาจตัดกลางคำ
     */
    titleLines: {
      text: string;
      accent?: boolean | null;
      id?: string | null;
    }[];
    subtitle: string;
    primaryButton: {
      label: string;
      /**
       * เช่น /shop หรือ https://...
       */
      href: string;
    };
    secondaryButton: {
      label: string;
      /**
       * เช่น /shop หรือ https://...
       */
      href: string;
    };
    image?: (number | null) | Media;
    imageCaption?: string | null;
    stats?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    /**
     * เลือกได้เฉพาะฟอนต์ที่โหลดมาพร้อมเว็บแล้ว จึงไม่ทำให้เว็บช้าลง
     */
    fontFamily?: ('theme' | 'plex-noto' | 'sarabun-trirong' | 'prompt') | null;
    /**
     * ย่อ-ขยายตัวอักษรทุกขนาดในส่วนนี้พร้อมกัน สัดส่วนหัวเรื่องกับเนื้อหาจึงไม่เพี้ยน
     */
    textScale?: ('0.9' | '0.95' | '1' | '1.1' | '1.2') | null;
    textAlign?: ('default' | 'left' | 'center' | 'right') | null;
    contentWidth?: ('default' | 'narrow' | 'medium' | 'full') | null;
    /**
     * ปรับระยะห่างบน-ล่างและช่องไฟระหว่างการ์ดในส่วนนี้
     */
    spacing?: ('default' | 'compact' | 'normal' | 'roomy') | null;
  };
  highlights?:
    | {
        icon: 'leaf' | 'temple' | 'mortar' | 'users' | 'map-pin';
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  /**
   * ลากเพื่อสลับลำดับ ติ๊กออกเพื่อซ่อน · แบนเนอร์บนสุดอยู่ตำแหน่งแรกเสมอ แก้ลำดับไม่ได้
   */
  sections?:
    | {
        type: 'highlights' | 'featured-products' | 'spotlight' | 'workshops' | 'latest-articles' | 'cta';
        enabled?: boolean | null;
        background?: ('page' | 'dark' | 'tint' | 'custom') | null;
        /**
         * ใส่เป็นรหัสสีแบบ #rrggbb
         */
        backgroundColor?: string | null;
        textTone?: ('auto' | 'light' | 'dark') | null;
        /**
         * เว้นว่างไว้เพื่อใช้สีหลักของธีม · ใส่แล้วจะเปลี่ยนสีปุ่ม ป้าย และหัวข้อเล็กเฉพาะในส่วนนี้
         */
        accentColor?: string | null;
        columns?: ('auto' | '2' | '3' | '4') | null;
        /**
         * เว้นว่างไว้เพื่อแสดงทั้งหมด
         */
        limit?: number | null;
        /**
         * เลือกได้เฉพาะฟอนต์ที่โหลดมาพร้อมเว็บแล้ว จึงไม่ทำให้เว็บช้าลง
         */
        fontFamily?: ('theme' | 'plex-noto' | 'sarabun-trirong' | 'prompt') | null;
        /**
         * ย่อ-ขยายตัวอักษรทุกขนาดในส่วนนี้พร้อมกัน สัดส่วนหัวเรื่องกับเนื้อหาจึงไม่เพี้ยน
         */
        textScale?: ('0.9' | '0.95' | '1' | '1.1' | '1.2') | null;
        textAlign?: ('default' | 'left' | 'center' | 'right') | null;
        contentWidth?: ('default' | 'narrow' | 'medium' | 'full') | null;
        /**
         * ปรับระยะห่างบน-ล่างและช่องไฟระหว่างการ์ดในส่วนนี้
         */
        spacing?: ('default' | 'compact' | 'normal' | 'roomy') | null;
        id?: string | null;
      }[]
    | null;
  featuredSection: {
    eyebrow?: string | null;
    title: string;
    description?: string | null;
  };
  experienceSection: {
    eyebrow?: string | null;
    title: string;
    description?: string | null;
  };
  storiesSection: {
    eyebrow?: string | null;
    title: string;
    description?: string | null;
  };
  spotlight?: {
    eyebrow?: string | null;
    /**
     * เว้นว่างได้ ระบบจะซ่อนส่วนนี้ไป
     */
    article?: (number | null) | Article;
    quote?: string | null;
    attribution?: string | null;
  };
  cta: {
    eyebrow?: string | null;
    title: string;
    body?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  hero: {
    eyebrow?: string | null;
    title: string;
    description?: string | null;
    /**
     * เลือกได้เฉพาะฟอนต์ที่โหลดมาพร้อมเว็บแล้ว จึงไม่ทำให้เว็บช้าลง
     */
    fontFamily?: ('theme' | 'plex-noto' | 'sarabun-trirong' | 'prompt') | null;
    /**
     * ย่อ-ขยายตัวอักษรทุกขนาดในส่วนนี้พร้อมกัน สัดส่วนหัวเรื่องกับเนื้อหาจึงไม่เพี้ยน
     */
    textScale?: ('0.9' | '0.95' | '1' | '1.1' | '1.2') | null;
    textAlign?: ('default' | 'left' | 'center' | 'right') | null;
    contentWidth?: ('default' | 'narrow' | 'medium' | 'full') | null;
    /**
     * ปรับระยะห่างบน-ล่างและช่องไฟระหว่างการ์ดในส่วนนี้
     */
    spacing?: ('default' | 'compact' | 'normal' | 'roomy') | null;
  };
  /**
   * ลากเพื่อสลับลำดับ ติ๊กออกเพื่อซ่อน · ส่วนที่ไม่ได้อยู่ในรายการนี้จะไม่แสดงบนหน้าเว็บ
   */
  sections?:
    | {
        type: 'history' | 'assets' | 'artisans' | 'closing' | 'references';
        enabled?: boolean | null;
        background?: ('page' | 'dark' | 'tint' | 'custom') | null;
        /**
         * ใส่เป็นรหัสสีแบบ #rrggbb
         */
        backgroundColor?: string | null;
        textTone?: ('auto' | 'light' | 'dark') | null;
        /**
         * เว้นว่างไว้เพื่อใช้สีหลักของธีม · ใส่แล้วจะเปลี่ยนสีปุ่ม ป้าย และหัวข้อเล็กเฉพาะในส่วนนี้
         */
        accentColor?: string | null;
        columns?: ('auto' | '2' | '3' | '4') | null;
        /**
         * เว้นว่างไว้เพื่อแสดงทั้งหมด
         */
        limit?: number | null;
        /**
         * เลือกได้เฉพาะฟอนต์ที่โหลดมาพร้อมเว็บแล้ว จึงไม่ทำให้เว็บช้าลง
         */
        fontFamily?: ('theme' | 'plex-noto' | 'sarabun-trirong' | 'prompt') | null;
        /**
         * ย่อ-ขยายตัวอักษรทุกขนาดในส่วนนี้พร้อมกัน สัดส่วนหัวเรื่องกับเนื้อหาจึงไม่เพี้ยน
         */
        textScale?: ('0.9' | '0.95' | '1' | '1.1' | '1.2') | null;
        textAlign?: ('default' | 'left' | 'center' | 'right') | null;
        contentWidth?: ('default' | 'narrow' | 'medium' | 'full') | null;
        /**
         * ปรับระยะห่างบน-ล่างและช่องไฟระหว่างการ์ดในส่วนนี้
         */
        spacing?: ('default' | 'compact' | 'normal' | 'roomy') | null;
        id?: string | null;
      }[]
    | null;
  historySection: {
    eyebrow?: string | null;
    title: string;
    description?: string | null;
  };
  historyImage?: (number | null) | Media;
  historyContent?:
    | (
        | {
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heading';
          }
        | {
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'paragraph';
          }
      )[]
    | null;
  facts?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  historyLink: {
    label: string;
    /**
     * เช่น /shop หรือ https://...
     */
    href: string;
  };
  assetsSection: {
    eyebrow?: string | null;
    title: string;
    description?: string | null;
  };
  assets?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  artisansSection: {
    eyebrow?: string | null;
    title: string;
    description?: string | null;
  };
  closing: {
    title: string;
    body?: string | null;
    image?: (number | null) | Media;
    primaryButton: {
      label: string;
      /**
       * เช่น /shop หรือ https://...
       */
      href: string;
    };
    secondaryButton: {
      label: string;
      /**
       * เช่น /shop หรือ https://...
       */
      href: string;
    };
  };
  /**
   * แสดงท้ายหน้า เพื่อให้ผู้อ่านตรวจสอบที่มาของข้อมูลได้
   */
  references?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-page".
 */
export interface ShopPage {
  id: number;
  hero: {
    eyebrow?: string | null;
    title: string;
    description?: string | null;
    /**
     * เลือกได้เฉพาะฟอนต์ที่โหลดมาพร้อมเว็บแล้ว จึงไม่ทำให้เว็บช้าลง
     */
    fontFamily?: ('theme' | 'plex-noto' | 'sarabun-trirong' | 'prompt') | null;
    /**
     * ย่อ-ขยายตัวอักษรทุกขนาดในส่วนนี้พร้อมกัน สัดส่วนหัวเรื่องกับเนื้อหาจึงไม่เพี้ยน
     */
    textScale?: ('0.9' | '0.95' | '1' | '1.1' | '1.2') | null;
    textAlign?: ('default' | 'left' | 'center' | 'right') | null;
    contentWidth?: ('default' | 'narrow' | 'medium' | 'full') | null;
    /**
     * ปรับระยะห่างบน-ล่างและช่องไฟระหว่างการ์ดในส่วนนี้
     */
    spacing?: ('default' | 'compact' | 'normal' | 'roomy') | null;
  };
  /**
   * หน้าสินค้ามีส่วนหลักคือรายการสินค้า เพิ่มกล่องชวนติดต่อท้ายหน้าได้
   */
  sections?:
    | {
        type: 'catalogue' | 'cta';
        enabled?: boolean | null;
        background?: ('page' | 'dark' | 'tint' | 'custom') | null;
        /**
         * ใส่เป็นรหัสสีแบบ #rrggbb
         */
        backgroundColor?: string | null;
        textTone?: ('auto' | 'light' | 'dark') | null;
        /**
         * เว้นว่างไว้เพื่อใช้สีหลักของธีม · ใส่แล้วจะเปลี่ยนสีปุ่ม ป้าย และหัวข้อเล็กเฉพาะในส่วนนี้
         */
        accentColor?: string | null;
        columns?: ('auto' | '2' | '3' | '4') | null;
        /**
         * เว้นว่างไว้เพื่อแสดงทั้งหมด
         */
        limit?: number | null;
        /**
         * เลือกได้เฉพาะฟอนต์ที่โหลดมาพร้อมเว็บแล้ว จึงไม่ทำให้เว็บช้าลง
         */
        fontFamily?: ('theme' | 'plex-noto' | 'sarabun-trirong' | 'prompt') | null;
        /**
         * ย่อ-ขยายตัวอักษรทุกขนาดในส่วนนี้พร้อมกัน สัดส่วนหัวเรื่องกับเนื้อหาจึงไม่เพี้ยน
         */
        textScale?: ('0.9' | '0.95' | '1' | '1.1' | '1.2') | null;
        textAlign?: ('default' | 'left' | 'center' | 'right') | null;
        contentWidth?: ('default' | 'narrow' | 'medium' | 'full') | null;
        /**
         * ปรับระยะห่างบน-ล่างและช่องไฟระหว่างการ์ดในส่วนนี้
         */
        spacing?: ('default' | 'compact' | 'normal' | 'roomy') | null;
        id?: string | null;
      }[]
    | null;
  emptyState: {
    title: string;
    body?: string | null;
  };
  /**
   * แสดงเมื่อเพิ่มส่วน "กล่องชวนติดต่อ" ไว้ในลำดับด้านบน
   */
  cta?: {
    eyebrow?: string | null;
    title?: string | null;
    body?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories-page".
 */
export interface StoriesPage {
  id: number;
  hero: {
    eyebrow?: string | null;
    title: string;
    description?: string | null;
    /**
     * เลือกได้เฉพาะฟอนต์ที่โหลดมาพร้อมเว็บแล้ว จึงไม่ทำให้เว็บช้าลง
     */
    fontFamily?: ('theme' | 'plex-noto' | 'sarabun-trirong' | 'prompt') | null;
    /**
     * ย่อ-ขยายตัวอักษรทุกขนาดในส่วนนี้พร้อมกัน สัดส่วนหัวเรื่องกับเนื้อหาจึงไม่เพี้ยน
     */
    textScale?: ('0.9' | '0.95' | '1' | '1.1' | '1.2') | null;
    textAlign?: ('default' | 'left' | 'center' | 'right') | null;
    contentWidth?: ('default' | 'narrow' | 'medium' | 'full') | null;
    /**
     * ปรับระยะห่างบน-ล่างและช่องไฟระหว่างการ์ดในส่วนนี้
     */
    spacing?: ('default' | 'compact' | 'normal' | 'roomy') | null;
  };
  /**
   * ลากเพื่อสลับลำดับ ติ๊กออกเพื่อซ่อน · ส่วนที่ไม่ได้อยู่ในรายการนี้จะไม่แสดงบนหน้าเว็บ
   */
  sections?:
    | {
        type: 'list' | 'cta';
        enabled?: boolean | null;
        background?: ('page' | 'dark' | 'tint' | 'custom') | null;
        /**
         * ใส่เป็นรหัสสีแบบ #rrggbb
         */
        backgroundColor?: string | null;
        textTone?: ('auto' | 'light' | 'dark') | null;
        /**
         * เว้นว่างไว้เพื่อใช้สีหลักของธีม · ใส่แล้วจะเปลี่ยนสีปุ่ม ป้าย และหัวข้อเล็กเฉพาะในส่วนนี้
         */
        accentColor?: string | null;
        columns?: ('auto' | '2' | '3' | '4') | null;
        /**
         * เว้นว่างไว้เพื่อแสดงทั้งหมด
         */
        limit?: number | null;
        /**
         * เลือกได้เฉพาะฟอนต์ที่โหลดมาพร้อมเว็บแล้ว จึงไม่ทำให้เว็บช้าลง
         */
        fontFamily?: ('theme' | 'plex-noto' | 'sarabun-trirong' | 'prompt') | null;
        /**
         * ย่อ-ขยายตัวอักษรทุกขนาดในส่วนนี้พร้อมกัน สัดส่วนหัวเรื่องกับเนื้อหาจึงไม่เพี้ยน
         */
        textScale?: ('0.9' | '0.95' | '1' | '1.1' | '1.2') | null;
        textAlign?: ('default' | 'left' | 'center' | 'right') | null;
        contentWidth?: ('default' | 'narrow' | 'medium' | 'full') | null;
        /**
         * ปรับระยะห่างบน-ล่างและช่องไฟระหว่างการ์ดในส่วนนี้
         */
        spacing?: ('default' | 'compact' | 'normal' | 'roomy') | null;
        id?: string | null;
      }[]
    | null;
  emptyState: {
    title: string;
    body?: string | null;
  };
  /**
   * แสดงเมื่อเพิ่มส่วน "กล่องชวนติดต่อ" ไว้ในลำดับด้านบน
   */
  cta?: {
    eyebrow?: string | null;
    title?: string | null;
    body?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tourism-page".
 */
export interface TourismPage {
  id: number;
  hero: {
    eyebrow?: string | null;
    title: string;
    description?: string | null;
    /**
     * เลือกได้เฉพาะฟอนต์ที่โหลดมาพร้อมเว็บแล้ว จึงไม่ทำให้เว็บช้าลง
     */
    fontFamily?: ('theme' | 'plex-noto' | 'sarabun-trirong' | 'prompt') | null;
    /**
     * ย่อ-ขยายตัวอักษรทุกขนาดในส่วนนี้พร้อมกัน สัดส่วนหัวเรื่องกับเนื้อหาจึงไม่เพี้ยน
     */
    textScale?: ('0.9' | '0.95' | '1' | '1.1' | '1.2') | null;
    textAlign?: ('default' | 'left' | 'center' | 'right') | null;
    contentWidth?: ('default' | 'narrow' | 'medium' | 'full') | null;
    /**
     * ปรับระยะห่างบน-ล่างและช่องไฟระหว่างการ์ดในส่วนนี้
     */
    spacing?: ('default' | 'compact' | 'normal' | 'roomy') | null;
  };
  /**
   * ลากเพื่อสลับลำดับ ติ๊กออกเพื่อซ่อน · ส่วนที่ไม่ได้อยู่ในรายการนี้จะไม่แสดงบนหน้าเว็บ
   */
  sections?:
    | {
        type: 'workshops' | 'places' | 'travel' | 'cta';
        enabled?: boolean | null;
        background?: ('page' | 'dark' | 'tint' | 'custom') | null;
        /**
         * ใส่เป็นรหัสสีแบบ #rrggbb
         */
        backgroundColor?: string | null;
        textTone?: ('auto' | 'light' | 'dark') | null;
        /**
         * เว้นว่างไว้เพื่อใช้สีหลักของธีม · ใส่แล้วจะเปลี่ยนสีปุ่ม ป้าย และหัวข้อเล็กเฉพาะในส่วนนี้
         */
        accentColor?: string | null;
        columns?: ('auto' | '2' | '3' | '4') | null;
        /**
         * เว้นว่างไว้เพื่อแสดงทั้งหมด
         */
        limit?: number | null;
        /**
         * เลือกได้เฉพาะฟอนต์ที่โหลดมาพร้อมเว็บแล้ว จึงไม่ทำให้เว็บช้าลง
         */
        fontFamily?: ('theme' | 'plex-noto' | 'sarabun-trirong' | 'prompt') | null;
        /**
         * ย่อ-ขยายตัวอักษรทุกขนาดในส่วนนี้พร้อมกัน สัดส่วนหัวเรื่องกับเนื้อหาจึงไม่เพี้ยน
         */
        textScale?: ('0.9' | '0.95' | '1' | '1.1' | '1.2') | null;
        textAlign?: ('default' | 'left' | 'center' | 'right') | null;
        contentWidth?: ('default' | 'narrow' | 'medium' | 'full') | null;
        /**
         * ปรับระยะห่างบน-ล่างและช่องไฟระหว่างการ์ดในส่วนนี้
         */
        spacing?: ('default' | 'compact' | 'normal' | 'roomy') | null;
        id?: string | null;
      }[]
    | null;
  workshopsSection: {
    eyebrow?: string | null;
    title: string;
    description?: string | null;
  };
  placesSection: {
    eyebrow?: string | null;
    title: string;
    description?: string | null;
  };
  travelSection: {
    eyebrow?: string | null;
    title: string;
    description?: string | null;
  };
  travelOptions?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  /**
   * แสดงเมื่อเพิ่มส่วน "กล่องชวนติดต่อ" ไว้ในลำดับด้านบน
   */
  cta?: {
    eyebrow?: string | null;
    title?: string | null;
    body?: string | null;
  };
  notice: {
    title: string;
    body: string;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  hero: {
    eyebrow?: string | null;
    title: string;
    description?: string | null;
    /**
     * เลือกได้เฉพาะฟอนต์ที่โหลดมาพร้อมเว็บแล้ว จึงไม่ทำให้เว็บช้าลง
     */
    fontFamily?: ('theme' | 'plex-noto' | 'sarabun-trirong' | 'prompt') | null;
    /**
     * ย่อ-ขยายตัวอักษรทุกขนาดในส่วนนี้พร้อมกัน สัดส่วนหัวเรื่องกับเนื้อหาจึงไม่เพี้ยน
     */
    textScale?: ('0.9' | '0.95' | '1' | '1.1' | '1.2') | null;
    textAlign?: ('default' | 'left' | 'center' | 'right') | null;
    contentWidth?: ('default' | 'narrow' | 'medium' | 'full') | null;
    /**
     * ปรับระยะห่างบน-ล่างและช่องไฟระหว่างการ์ดในส่วนนี้
     */
    spacing?: ('default' | 'compact' | 'normal' | 'roomy') | null;
  };
  /**
   * ลากเพื่อสลับลำดับ ติ๊กออกเพื่อซ่อน · ส่วนที่ไม่ได้อยู่ในรายการนี้จะไม่แสดงบนหน้าเว็บ
   */
  sections?:
    | {
        type: 'channels' | 'form';
        enabled?: boolean | null;
        background?: ('page' | 'dark' | 'tint' | 'custom') | null;
        /**
         * ใส่เป็นรหัสสีแบบ #rrggbb
         */
        backgroundColor?: string | null;
        textTone?: ('auto' | 'light' | 'dark') | null;
        /**
         * เว้นว่างไว้เพื่อใช้สีหลักของธีม · ใส่แล้วจะเปลี่ยนสีปุ่ม ป้าย และหัวข้อเล็กเฉพาะในส่วนนี้
         */
        accentColor?: string | null;
        columns?: ('auto' | '2' | '3' | '4') | null;
        /**
         * เว้นว่างไว้เพื่อแสดงทั้งหมด
         */
        limit?: number | null;
        /**
         * เลือกได้เฉพาะฟอนต์ที่โหลดมาพร้อมเว็บแล้ว จึงไม่ทำให้เว็บช้าลง
         */
        fontFamily?: ('theme' | 'plex-noto' | 'sarabun-trirong' | 'prompt') | null;
        /**
         * ย่อ-ขยายตัวอักษรทุกขนาดในส่วนนี้พร้อมกัน สัดส่วนหัวเรื่องกับเนื้อหาจึงไม่เพี้ยน
         */
        textScale?: ('0.9' | '0.95' | '1' | '1.1' | '1.2') | null;
        textAlign?: ('default' | 'left' | 'center' | 'right') | null;
        contentWidth?: ('default' | 'narrow' | 'medium' | 'full') | null;
        /**
         * ปรับระยะห่างบน-ล่างและช่องไฟระหว่างการ์ดในส่วนนี้
         */
        spacing?: ('default' | 'compact' | 'normal' | 'roomy') | null;
        id?: string | null;
      }[]
    | null;
  channels?:
    | {
        channel: 'line' | 'phone' | 'facebook' | 'email';
        label: string;
        note: string;
        highlight?: boolean | null;
        id?: string | null;
      }[]
    | null;
  formSection: {
    eyebrow?: string | null;
    title: string;
    description?: string | null;
  };
  formTopics: {
    value: string;
    id?: string | null;
  }[];
  formSuccess: {
    title: string;
    body: string;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "not-found-page".
 */
export interface NotFoundPage {
  id: number;
  title: string;
  description: string;
  buttons?:
    | {
        label: string;
        /**
         * เช่น /shop หรือ https://...
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  communityName?: T;
  communityShortName?: T;
  tagline?: T;
  logo?: T;
  favicon?: T;
  aboutSummary?: T;
  phone?: T;
  phoneDisplay?: T;
  lineId?: T;
  lineUrl?: T;
  facebookUrl?: T;
  email?: T;
  address?: T;
  addressLocality?: T;
  addressRegion?: T;
  postalCode?: T;
  mapLatitude?: T;
  mapLongitude?: T;
  openingHours?: T;
  openingHoursShort?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  mainMenu?:
    | T
    | {
        label?: T;
        linkType?: T;
        page?: T;
        customPage?: T;
        url?: T;
        children?:
          | T
          | {
              label?: T;
              linkType?: T;
              page?: T;
              customPage?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  headerCta?:
    | T
    | {
        enabled?: T;
        label?: T;
        action?: T;
      };
  mobileMenu?:
    | T
    | {
        title?: T;
        contactHeading?: T;
        lineButtonPrefix?: T;
        phoneButtonPrefix?: T;
      };
  footerColumns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              linkType?: T;
              page?: T;
              customPage?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme_select".
 */
export interface ThemeSelect<T extends boolean = true> {
  palette?: T;
  accentColor?: T;
  surface?: T;
  fontPair?: T;
  baseFontSize?: T;
  radius?: T;
  density?: T;
  customCss?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ui-labels_select".
 */
export interface UiLabelsSelect<T extends boolean = true> {
  general?:
    | T
    | {
        askPrice?: T;
        askServicePrice?: T;
        viewAllProducts?: T;
        viewAllWorkshops?: T;
        viewAllArticles?: T;
        readFullArticle?: T;
        openInMaps?: T;
      };
  product?:
    | T
    | {
        madeBy?: T;
        viewArtisans?: T;
        specs?: T;
        sku?: T;
        form?: T;
        netContent?: T;
        mainHerbs?: T;
        shelfLife?: T;
        externalUseTitle?: T;
        externalUseBody?: T;
        callGroup?: T;
        facebookHint?: T;
        storyEyebrow?: T;
        storyTitle?: T;
        usageEyebrow?: T;
        usageTitle?: T;
        careEyebrow?: T;
        careTitle?: T;
        relatedEyebrow?: T;
        relatedTitle?: T;
        filters?: T;
        sortBy?: T;
        resultsUnit?: T;
      };
  article?:
    | T
    | {
        writtenBy?: T;
        readTime?: T;
        minutes?: T;
        share?: T;
        aboutAuthor?: T;
        aboutCommunityButton?: T;
        relatedEyebrow?: T;
        relatedTitle?: T;
        resultsUnit?: T;
      };
  tourism?:
    | T
    | {
        duration?: T;
        participants?: T;
        participantsUnit?: T;
        price?: T;
        perPerson?: T;
        bookingTerms?: T;
        takeaway?: T;
        bookViaLine?: T;
        callToBook?: T;
      };
  contact?:
    | T
    | {
        location?: T;
        openingHours?: T;
        coordinates?: T;
        contactCommunity?: T;
        directions?: T;
        copyright?: T;
      };
  about?:
    | T
    | {
        role?: T;
        source?: T;
        references?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-settings_select".
 */
export interface SeoSettingsSelect<T extends boolean = true> {
  keywords?:
    | T
    | {
        value?: T;
        id?: T;
      };
  defaultOgImage?: T;
  ga4MeasurementId?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        titleLines?:
          | T
          | {
              text?: T;
              accent?: T;
              id?: T;
            };
        subtitle?: T;
        primaryButton?:
          | T
          | {
              label?: T;
              href?: T;
            };
        secondaryButton?:
          | T
          | {
              label?: T;
              href?: T;
            };
        image?: T;
        imageCaption?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        fontFamily?: T;
        textScale?: T;
        textAlign?: T;
        contentWidth?: T;
        spacing?: T;
      };
  highlights?:
    | T
    | {
        icon?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        type?: T;
        enabled?: T;
        background?: T;
        backgroundColor?: T;
        textTone?: T;
        accentColor?: T;
        columns?: T;
        limit?: T;
        fontFamily?: T;
        textScale?: T;
        textAlign?: T;
        contentWidth?: T;
        spacing?: T;
        id?: T;
      };
  featuredSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  experienceSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  storiesSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  spotlight?:
    | T
    | {
        eyebrow?: T;
        article?: T;
        quote?: T;
        attribution?: T;
      };
  cta?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        body?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        fontFamily?: T;
        textScale?: T;
        textAlign?: T;
        contentWidth?: T;
        spacing?: T;
      };
  sections?:
    | T
    | {
        type?: T;
        enabled?: T;
        background?: T;
        backgroundColor?: T;
        textTone?: T;
        accentColor?: T;
        columns?: T;
        limit?: T;
        fontFamily?: T;
        textScale?: T;
        textAlign?: T;
        contentWidth?: T;
        spacing?: T;
        id?: T;
      };
  historySection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  historyImage?: T;
  historyContent?:
    | T
    | {
        heading?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        paragraph?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
      };
  facts?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  historyLink?:
    | T
    | {
        label?: T;
        href?: T;
      };
  assetsSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  assets?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  artisansSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  closing?:
    | T
    | {
        title?: T;
        body?: T;
        image?: T;
        primaryButton?:
          | T
          | {
              label?: T;
              href?: T;
            };
        secondaryButton?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  references?:
    | T
    | {
        value?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-page_select".
 */
export interface ShopPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        fontFamily?: T;
        textScale?: T;
        textAlign?: T;
        contentWidth?: T;
        spacing?: T;
      };
  sections?:
    | T
    | {
        type?: T;
        enabled?: T;
        background?: T;
        backgroundColor?: T;
        textTone?: T;
        accentColor?: T;
        columns?: T;
        limit?: T;
        fontFamily?: T;
        textScale?: T;
        textAlign?: T;
        contentWidth?: T;
        spacing?: T;
        id?: T;
      };
  emptyState?:
    | T
    | {
        title?: T;
        body?: T;
      };
  cta?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        body?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories-page_select".
 */
export interface StoriesPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        fontFamily?: T;
        textScale?: T;
        textAlign?: T;
        contentWidth?: T;
        spacing?: T;
      };
  sections?:
    | T
    | {
        type?: T;
        enabled?: T;
        background?: T;
        backgroundColor?: T;
        textTone?: T;
        accentColor?: T;
        columns?: T;
        limit?: T;
        fontFamily?: T;
        textScale?: T;
        textAlign?: T;
        contentWidth?: T;
        spacing?: T;
        id?: T;
      };
  emptyState?:
    | T
    | {
        title?: T;
        body?: T;
      };
  cta?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        body?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tourism-page_select".
 */
export interface TourismPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        fontFamily?: T;
        textScale?: T;
        textAlign?: T;
        contentWidth?: T;
        spacing?: T;
      };
  sections?:
    | T
    | {
        type?: T;
        enabled?: T;
        background?: T;
        backgroundColor?: T;
        textTone?: T;
        accentColor?: T;
        columns?: T;
        limit?: T;
        fontFamily?: T;
        textScale?: T;
        textAlign?: T;
        contentWidth?: T;
        spacing?: T;
        id?: T;
      };
  workshopsSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  placesSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  travelSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  travelOptions?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        body?: T;
      };
  notice?:
    | T
    | {
        title?: T;
        body?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        fontFamily?: T;
        textScale?: T;
        textAlign?: T;
        contentWidth?: T;
        spacing?: T;
      };
  sections?:
    | T
    | {
        type?: T;
        enabled?: T;
        background?: T;
        backgroundColor?: T;
        textTone?: T;
        accentColor?: T;
        columns?: T;
        limit?: T;
        fontFamily?: T;
        textScale?: T;
        textAlign?: T;
        contentWidth?: T;
        spacing?: T;
        id?: T;
      };
  channels?:
    | T
    | {
        channel?: T;
        label?: T;
        note?: T;
        highlight?: T;
        id?: T;
      };
  formSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  formTopics?:
    | T
    | {
        value?: T;
        id?: T;
      };
  formSuccess?:
    | T
    | {
        title?: T;
        body?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "not-found-page_select".
 */
export interface NotFoundPageSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  buttons?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}